"""The type table in the documentation, tied to the code that produces it.

`docs/users/guide/columns.md` publishes a three-column table —Postgres, MySQL, SQLite— with the SQL
type for every Python type. It is one of the most consulted pages of the guide and until now it was
maintained BY HAND: regenerated by looking at the code, and drifting between one regeneration and
the next.

It had already drifted. It claimed MySQL "rejects" a `SnakeUtc`, a `timedelta` and a `list[int]`
when all three fall back to TEXT ever since the fallback exists, and it did not mention `CHAR(n)`,
`REAL` or `TIMETZ`.

The project already has three documentation nets —that the snippets have valid syntax, that the
imported names exist, and that every documented model COMPILES—. None of them looks at a table,
because a table is not code. This is the fourth: it reads the rows and asks the dialect.

It is tied through the DECLARATOR the table itself publishes, so the row documents what you have to
write and, at the same time, is the test's input. A new row with no entry here also fails: a
half-finished table lies just as much as a wrong one.
"""

from __future__ import annotations

import pathlib
from datetime import date, datetime, time, timedelta
from decimal import Decimal
from uuid import UUID

import pytest

from snakeorm import (
    MySQLDialect,
    PostgresDialect,
    SnakeColumn,
    SnakeDialect,
    SQLiteDialect,
    snake_auto,
    snake_column,
    snake_datetime,
    snake_datetimetz,
    snake_decimal,
    snake_float,
    snake_int,
    snake_json,
    snake_str,
    snake_time,
    snake_timetz,
)
from snakeorm.compiler import compile_model
from snakeorm.migration.ddl import sql_type_of
from snakeorm.times import SnakeUtc

_DOCS = (
    pathlib.Path("docs/users/guide/columns.md"),  # English: the site's default language
    pathlib.Path("docs/users/guide/columns.es.md"),
)
"""BOTH pages. Tying only one leaves the other free to age, and that already happened: the English
table fell three types behind while the Spanish one was kept up to date, and nobody saw it because
the test looked at a single one."""

# Declarator exactly as the table publishes it -> (annotation, how that column is built).
# The key is the EXACT text of the cell: if somebody changes the documented declarator without
# changing the code (or the other way round), the row is left with no entry and the test says so.
_ROWS: dict[str, tuple[object, object]] = {
    "snake_int()": (SnakeColumn[int], snake_int()),
    "snake_auto()": (SnakeColumn[int], snake_auto()),
    "snake_str(max_length=50)": (SnakeColumn[str], snake_str(max_length=50)),
    "snake_str(max_length=2, fixed=True)": (
        SnakeColumn[str],
        snake_str(max_length=2, fixed=True),
    ),
    "snake_float()": (SnakeColumn[float], snake_float()),
    "snake_float(size=4)": (SnakeColumn[float], snake_float(size=4)),
    "snake_decimal(precision=12, scale=2)": (
        SnakeColumn[Decimal],
        snake_decimal(precision=12, scale=2),
    ),
    "snake_datetimetz()": (SnakeColumn[SnakeUtc], snake_datetimetz()),
    "snake_datetime()": (SnakeColumn[datetime], snake_datetime()),
    "snake_time()": (SnakeColumn[time], snake_time()),
    "snake_timetz()": (SnakeColumn[time], snake_timetz()),
    "snake_json()": (SnakeColumn[dict], snake_json()),
}
"""The rows with a declarator of their own. The `snake_column()` ones are resolved by the row's
type, because that declarator serves every type WITHOUT parameters and identifies none of them.

The whole ANNOTATION is stored (`SnakeColumn[int]`) and not the bare type: subscripting with a
variable is not a valid annotation for the checker, and this file goes through the same strict gate
as the rest — a test that needs a `type: ignore` in order to exist is usually telling you something."""

_SIN_PARAMETROS: dict[str, object] = {
    "`bool`": SnakeColumn[bool],
    "`date`": SnakeColumn[date],
    "`timedelta`": SnakeColumn[timedelta],
    "`UUID`": SnakeColumn[UUID],
    "`bytes`": SnakeColumn[bytes],
    "`list[int]`": SnakeColumn[list[int]],
}

_DIALECTOS: dict[str, SnakeDialect] = {
    "PostgreSQL": PostgresDialect(),
    "MySQL": MySQLDialect(),
    "SQLite": SQLiteDialect(),
}


def _emitted_type(
    dialect: SnakeDialect, annotation: object, especificador: object
) -> str:
    """The SQL type that column really emits, compiling the model the way the user would."""
    model = type(
        "M",
        (),
        {
            "__annotations__": {"id": SnakeColumn[int], "c": annotation},
            "id": snake_auto(),
            "c": especificador,
        },
    )
    column = compile_model(model).get_column("c")
    assert column is not None
    return sql_type_of(column, dialect)


def _documented_rows(
    doc: pathlib.Path,
) -> list[tuple[str, str, str, dict[str, str]]]:
    """The rows of the type table: (page, Python type, declarator, {engine: SQL type})."""
    text = doc.read_text(encoding="utf-8")
    rows: list[tuple[str, str, str, dict[str, str]]] = []
    for line in text.splitlines():
        celdas = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(celdas) != 5 or celdas[0] in ("Python", "") or set(celdas[0]) <= {"-"}:
            continue
        declarador = celdas[1].strip("`")
        if not declarador.startswith("snake_"):
            continue
        rows.append(
            (
                doc.name,
                celdas[0],
                declarador,
                dict(zip(_DIALECTOS, celdas[2:], strict=True)),
            )
        )
    return rows


def _all_rows() -> list[tuple[str, str, str, dict[str, str]]]:
    """The rows of BOTH pages, so that neither is left unwatched."""
    return [row for doc in _DOCS for row in _documented_rows(doc)]


@pytest.mark.parametrize("doc", _DOCS, ids=lambda p: p.name)
def test_the_documented_table_was_actually_found(doc: pathlib.Path) -> None:
    """The table exists and has rows, in EACH language. Without this, the rest would pass vacuously.

    It is the classic trap of a test that parses documentation: if the parser stops finding anything,
    "all the rows match" holds vacuously and the test passes without checking a single one.
    """
    rows = _documented_rows(doc)

    assert len(rows) >= 15, f"only {len(rows)} type rows were found in {doc}"


def test_both_languages_document_the_same_types() -> None:
    """Both tables list the SAME declarators. This is the net against drift between languages.

    That every cell matches the dialect is already checked by the test below; what is watched here
    is that no ROW is missing in one language. Adding a type and half-translating it leaves the
    reader of one language with a table that lies by omission, and no per-cell check sees that.
    """
    por_pagina = {doc.name: {row[2] for row in _documented_rows(doc)} for doc in _DOCS}
    (una, otra) = por_pagina.values()

    assert una == otra, (
        f"the type tables do not match between languages. Only in one: {sorted(una - otra)}; "
        f"only in the other: {sorted(otra - una)}"
    )


@pytest.mark.parametrize(
    ("pagina", "doc_type", "declarador", "expected_by_engine"),
    _all_rows(),
    ids=lambda v: v if isinstance(v, str) else "",
)
def test_every_documented_type_matches_what_the_dialect_emits(
    pagina: str, doc_type: str, declarador: str, expected_by_engine: dict[str, str]
) -> None:
    """Every cell of the table says what the dialect really emits, engine by engine.

    This is the net that was missing: the table was regenerated by hand and already carried three
    stale rows. An out-of-date type table lies just as much as an out-of-date type — and this is the
    page everybody looks at before declaring a column.
    """
    if declarador == "snake_column()":
        annotation = _SIN_PARAMETROS[doc_type]
        especificador = snake_column()
    else:
        annotation, especificador = _ROWS[f"{declarador}"]

    for engine, expected in expected_by_engine.items():
        emitted = _emitted_type(_DIALECTOS[engine], annotation, especificador)

        assert emitted == expected.strip("`"), (
            f"{pagina} says that {doc_type} with {declarador} is {expected} on {engine}, and the "
            f"dialect emits {emitted!r}"
        )
