"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import snakeorm.times


from snakeorm.metadata import (
    SnakeDateTimeParams,
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeTableInfo,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_auth_initial"

api_tokens = SnakeTableInfo(
    name="api_tokens",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="token", python_type=str, unique=True, attr_name="token"),
        SnakeColumnInfo(
            name="label",
            python_type=str,
            nullable=True,
            attr_name="label",
        ),
        SnakeColumnInfo(
            name="revoked",
            python_type=bool,
            default=False,
            has_default=True,
            attr_name="revoked",
        ),
        SnakeColumnInfo(
            name="user_id",
            python_type=int,
            index=True,
            attr_name="user_id",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="expires_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="expires_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("user_id",)),),
)

login_sessions = SnakeTableInfo(
    name="login_sessions",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="user_id",
            python_type=int,
            index=True,
            attr_name="user_id",
        ),
        SnakeColumnInfo(name="ip", python_type=str, attr_name="ip"),
        SnakeColumnInfo(
            name="user_agent",
            python_type=str,
            nullable=True,
            attr_name="user_agent",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="last_seen_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="last_seen_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("user_id",)),),
)

users = SnakeTableInfo(
    name="users",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="username",
            python_type=str,
            unique=True,
            attr_name="username",
        ),
        SnakeColumnInfo(name="email", python_type=str, unique=True, attr_name="email"),
        SnakeColumnInfo(
            name="password_hash",
            python_type=str,
            attr_name="password_hash",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="roles",
            target="Role",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.roles",
        ),
        SnakeRelationshipInfo(
            name="api_tokens",
            target="ApiToken",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.api_tokens",
        ),
        SnakeRelationshipInfo(
            name="sessions",
            target="LoginSession",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.login_sessions",
        ),
        SnakeRelationshipInfo(
            name="blogs",
            target="Blog",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("owner_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="posts",
            target="Post",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="subscriptions",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.subscriptions",
        ),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(api_tokens),
    CreateTable(login_sessions),
    AddForeignKey(
        api_tokens,
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        users,
    ),
    AddForeignKey(
        login_sessions,
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        users,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
