"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import datetime
import decimal
import shared.models.inventory_models
import snakeorm.times
import uuid

from snakeorm.metadata import (
    SnakeCheckInfo,
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeDecimalParams,
    SnakeEnumStorage,
    SnakeFloatParams,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakeIntParams,
    SnakeIntSize,
    SnakeJsonParams,
    SnakeJsonStorage,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeStrParams,
    SnakeTableInfo,
    SnakeTimeParams,
)
from snakeorm.expressions import (
    SnakeComparison,
    SnakeExpr,
    SnakeInList,
    SnakeOp,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_inventory_initial"

skus = SnakeTableInfo(
    name="skus",
    columns=(
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="public_id",
            python_type=uuid.UUID,
            attr_name="public_id",
            default_factory=uuid.uuid4,
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            attr_name="name",
            type_params=SnakeStrParams(max_length=120, fixed=False),
        ),
        SnakeColumnInfo(
            name="kind",
            python_type=shared.models.inventory_models.SkuKind,
            default="physical",
            has_default=True,
            attr_name="kind",
            enum_type=shared.models.inventory_models.SkuKind,
            enum_storage=SnakeEnumStorage.CHECK,
        ),
        SnakeColumnInfo(
            name="price",
            python_type=decimal.Decimal,
            attr_name="price",
            type_params=SnakeDecimalParams(precision=12, scale=2),
        ),
        SnakeColumnInfo(
            name="weight_kg",
            python_type=float,
            attr_name="weight_kg",
            type_params=SnakeFloatParams(size=4),
        ),
        SnakeColumnInfo(
            name="lead_time",
            python_type=datetime.timedelta,
            attr_name="lead_time",
        ),
        SnakeColumnInfo(
            name="thumbnail",
            python_type=bytes,
            nullable=True,
            default=None,
            has_default=True,
            attr_name="thumbnail",
        ),
        SnakeColumnInfo(
            name="attrs",
            python_type=dict,
            attr_name="attrs",
            type_params=SnakeJsonParams(storage=SnakeJsonStorage.JSONB),
        ),
        SnakeColumnInfo(
            name="related_ids",
            python_type=list[int],
            attr_name="related_ids",
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.warehouse_stock",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeInList(
                SnakeExpr(path=("kind",)),
                ("physical", "digital", "service"),
            ),
        ),
    ),
    db_comment="Catalogue of stockable items",
)

stock_movements = SnakeTableInfo(
    name="stock_movements",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="stock_warehouse_id",
            python_type=int,
            attr_name="stock_warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="stock_sku_id",
            python_type=int,
            attr_name="stock_sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="delta",
            python_type=int,
            attr_name="delta",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reason",
            python_type=shared.models.inventory_models.MovementReason,
            default="adjustment",
            has_default=True,
            attr_name="reason",
            enum_type=shared.models.inventory_models.MovementReason,
            enum_storage=SnakeEnumStorage.CHECK,
        ),
        SnakeColumnInfo(
            name="note",
            python_type=str,
            nullable=True,
            default=None,
            has_default=True,
            attr_name="note",
            type_params=SnakeStrParams(max_length=200, fixed=False),
        ),
        SnakeColumnInfo(
            name="happened_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="happened_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Stock",
                pairs=(
                    ("stock_warehouse_id", "warehouse_id"),
                    ("stock_sku_id", "sku_id"),
                ),
            ),
            target_table="public.warehouse_stock",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeInList(
                SnakeExpr(path=("reason",)),
                ("purchase", "sale", "return", "adjustment"),
            ),
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("stock_warehouse_id", "stock_sku_id")),),
)

warehouse_stock = SnakeTableInfo(
    name="warehouse_stock",
    columns=(
        SnakeColumnInfo(
            name="warehouse_id",
            python_type=int,
            attr_name="warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="sku_id",
            python_type=int,
            attr_name="sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="quantity",
            python_type=int,
            attr_name="quantity",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            default=0,
            has_default=True,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="counted_at",
            python_type=snakeorm.times.SnakeUtc,
            nullable=True,
            attr_name="counted_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="warehouse_id",
                python_type=int,
                attr_name="warehouse_id",
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
            SnakeColumnInfo(
                name="sku_id",
                python_type=int,
                attr_name="sku_id",
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="warehouse",
            target="Warehouse",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouses",
        ),
        SnakeRelationshipInfo(
            name="sku",
            target="Sku",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.skus",
        ),
        SnakeRelationshipInfo(
            name="movements",
            target="StockMovement",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Stock",
                pairs=(
                    ("stock_warehouse_id", "warehouse_id"),
                    ("stock_sku_id", "sku_id"),
                ),
            ),
            target_table="public.stock_movements",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("quantity",)), SnakeOp.GE, 0),
            name="ck_warehouse_stock_quantity_not_negative",
        ),
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("reserved",)), SnakeOp.GE, 0),
            name="ck_warehouse_stock_reserved_not_negative",
        ),
    ),
    db_comment="Stock of one SKU in one warehouse",
)

warehouses = SnakeTableInfo(
    name="warehouses",
    columns=(
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="code",
            python_type=str,
            unique=True,
            attr_name="code",
            type_params=SnakeStrParams(max_length=3, fixed=True),
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            attr_name="name",
            type_params=SnakeStrParams(max_length=80, fixed=False),
        ),
        SnakeColumnInfo(
            name="active",
            python_type=bool,
            default=True,
            has_default=True,
            attr_name="active",
        ),
        SnakeColumnInfo(
            name="opened_on",
            python_type=datetime.date,
            attr_name="opened_on",
        ),
        SnakeColumnInfo(
            name="shift_start",
            python_type=datetime.time,
            attr_name="shift_start",
            type_params=SnakeTimeParams(with_timezone=False),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouse_stock",
        ),
    ),
    db_comment="Physical warehouses that hold stock",
    indexes=(
        SnakeIndexInfo(
            columns=("code",),
            name="ix_warehouses_active_code",
            where=SnakeComparison(SnakeExpr(path=("active",)), SnakeOp.EQ, True),
        ),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(skus),
    CreateTable(stock_movements),
    CreateTable(warehouse_stock),
    CreateTable(warehouses),
    AddForeignKey(
        stock_movements,
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Stock",
                pairs=(
                    ("stock_warehouse_id", "warehouse_id"),
                    ("stock_sku_id", "sku_id"),
                ),
            ),
            target_table="public.warehouse_stock",
        ),
        warehouse_stock,
    ),
    AddForeignKey(
        warehouse_stock,
        SnakeRelationshipInfo(
            name="sku",
            target="Sku",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.skus",
        ),
        skus,
    ),
    AddForeignKey(
        warehouse_stock,
        SnakeRelationshipInfo(
            name="warehouse",
            target="Warehouse",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouses",
        ),
        warehouses,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
