"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import datetime
import snakeorm.times

from snakeorm.metadata import (
    SnakeCheckInfo,
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeStrParams,
    SnakeTableInfo,
    SnakeTimeParams,
)
from snakeorm.expressions import (
    SnakeComparison,
    SnakeExpr,
    SnakeOp,
)
from snakeorm.migration import (
    AddColumn,
    Migration,
    SnakeOperation,
)

version = "0002_inventory_clocks"

warehouse_stock = SnakeTableInfo(
    name="warehouse_stock",
    columns=(
        SnakeColumnInfo(
            name="warehouse_id",
            python_type=int,
            attr_name="warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="sku_id",
            python_type=int,
            attr_name="sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="quantity",
            python_type=int,
            attr_name="quantity",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            default=0,
            has_default=True,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="counted_at",
            python_type=snakeorm.times.SnakeUtc,
            nullable=True,
            attr_name="counted_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="counted_local",
            python_type=datetime.datetime,
            nullable=True,
            attr_name="counted_local",
            type_params=SnakeDateTimeParams(tz=False, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="warehouse_id",
                python_type=int,
                attr_name="warehouse_id",
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
            SnakeColumnInfo(
                name="sku_id",
                python_type=int,
                attr_name="sku_id",
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="warehouse",
            target="Warehouse",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouses",
        ),
        SnakeRelationshipInfo(
            name="sku",
            target="Sku",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.skus",
        ),
        SnakeRelationshipInfo(
            name="movements",
            target="StockMovement",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Stock",
                pairs=(
                    ("stock_warehouse_id", "warehouse_id"),
                    ("stock_sku_id", "sku_id"),
                ),
            ),
            target_table="public.stock_movements",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("quantity",)), SnakeOp.GE, 0),
            name="ck_warehouse_stock_quantity_not_negative",
        ),
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("reserved",)), SnakeOp.GE, 0),
            name="ck_warehouse_stock_reserved_not_negative",
        ),
    ),
    db_comment="Stock of one SKU in one warehouse",
)

warehouses = SnakeTableInfo(
    name="warehouses",
    columns=(
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="code",
            python_type=str,
            unique=True,
            attr_name="code",
            type_params=SnakeStrParams(max_length=3, fixed=True),
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            attr_name="name",
            type_params=SnakeStrParams(max_length=80, fixed=False),
        ),
        SnakeColumnInfo(
            name="active",
            python_type=bool,
            default=True,
            has_default=True,
            attr_name="active",
        ),
        SnakeColumnInfo(
            name="opened_on",
            python_type=datetime.date,
            attr_name="opened_on",
        ),
        SnakeColumnInfo(
            name="shift_start",
            python_type=datetime.time,
            attr_name="shift_start",
            type_params=SnakeTimeParams(with_timezone=False),
        ),
        SnakeColumnInfo(
            name="cutoff",
            python_type=datetime.time,
            attr_name="cutoff",
            type_params=SnakeTimeParams(with_timezone=True),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouse_stock",
        ),
    ),
    db_comment="Physical warehouses that hold stock",
    indexes=(
        SnakeIndexInfo(
            columns=("code",),
            name="ix_warehouses_active_code",
            where=SnakeComparison(SnakeExpr(path=("active",)), SnakeOp.EQ, True),
        ),
    ),
)

operations: list[SnakeOperation] = [
    AddColumn(
        warehouse_stock,
        SnakeColumnInfo(
            name="counted_local",
            python_type=datetime.datetime,
            nullable=True,
            attr_name="counted_local",
            type_params=SnakeDateTimeParams(tz=False, precision=None),
        ),
    ),
    AddColumn(
        warehouses,
        SnakeColumnInfo(
            name="cutoff",
            python_type=datetime.time,
            attr_name="cutoff",
            type_params=SnakeTimeParams(with_timezone=True),
        ),
    ),
]

migration = Migration(version=version, operations=tuple(operations))
