"""Migration generated by SnakeORM. Editable by hand.

THE BODY OF THIS VIEW IS WRITTEN PORTABLY, BY HAND, and that is the whole edit. `makemigrations`
froze the SELECT the way ONE engine renders it —
`SELECT "warehouse_id", ... FROM "public"."warehouse_stock" WHERE "quantity" < 10` — and that string
is not SQL the three engines share: `public` is a Postgres schema and SQLite has none, so the server
answers «view "low_stock" cannot reference objects in database public». `realize` accepts the plan
because the shape of a `CreateView` is fine everywhere; what it cannot inspect is the SQL the
operation CARRIES.

Unqualified, unquoted, lower-case identifiers are the intersection of the three: no schema to
resolve, and no quoting character to disagree about (Postgres and SQLite quote with `"`, MySQL with
`` ` `` unless `ANSI_QUOTES` is on). The FINAL shape of this view — `0005` — does not need the trick:
it carries a `view_query` and the emitter renders it per dialect, which is the mechanism the ORM
already has. This one cannot, because it describes the view as it was when the column was still
called `quantity`, and no model says that any more.
"""

from __future__ import annotations

import datetime
import snakeorm.times

from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
    SnakeTableKind,
)
from snakeorm.migration import (
    CreateView,
    Migration,
    SnakeOperation,
)

version = "0003_inventory_low_stock_view"

low_stock = SnakeTableInfo(
    name="low_stock",
    columns=(
        SnakeColumnInfo(
            name="warehouse_id",
            python_type=int,
            attr_name="warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="sku_id",
            python_type=int,
            attr_name="sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="quantity",
            python_type=int,
            attr_name="quantity",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="counted_at",
            python_type=snakeorm.times.SnakeUtc,
            nullable=True,
            attr_name="counted_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="counted_local",
            python_type=datetime.datetime,
            nullable=True,
            attr_name="counted_local",
            type_params=SnakeDateTimeParams(tz=False, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(columns=()),
    kind=SnakeTableKind.VIEW,
    view_definition="SELECT warehouse_id, sku_id, quantity, reserved, counted_at, counted_local FROM warehouse_stock WHERE quantity < 10",
)

operations: list[SnakeOperation] = [
    CreateView(low_stock),
]

migration = Migration(version=version, operations=tuple(operations))
