"""Migration generated by SnakeORM. Editable by hand.

Two changes with one cause. `LowStock` used to ask `on_hand < 10` — what is on the SHELF — and the
question a replenishment dashboard needs is what is AVAILABLE: a pair holding fifty units of which
forty-five are promised has five, and the old view never mentioned it.

That question could not be WRITTEN until the ORM learned to compare a column against a column. Once
it could, `on_hand` stopped being a good name: with `reserved` beside it, it does not say whether
the reserved units are inside it. Warehouse vocabulary has three words for three numbers — on hand,
reserved, and available = on hand - reserved — so the column takes the first.

WHY THE RENAME IS WRITTEN BY HAND. The autodetector does not infer one: it sees a `DropColumn` and an
`AddColumn` and says so, and applying that pair would DELETE the column and create an empty one. It
does offer `rename_suggestions()`, which named this pair unambiguously — `('warehouse_stock',
'on_hand', 'on_hand')` — and turning a suggestion into a decision is the author's job, not the
tool's. This file is that decision.

The CHECK is renamed with the column: a constraint called `..._quantity_not_negative` over a column
called `on_hand` is a name that lies from the day of the rename.

WHY THE CONSTRAINT SWAP IS A `RebuildTable` AND NOT A `DropCheck`/`AddCheck` PAIR. SQLite has no
`ALTER TABLE ... DROP CONSTRAINT` and never will, so the pair is refused there — `Cap.ADD_CONSTRAINT`
— and this file was the first place the whole history stopped on that engine. A `RebuildTable` says
the same thing engine-agnostically: the table goes from THIS constraint shape to THAT one. Postgres
and MariaDB still get the two minimal `ALTER`s, byte for byte what the pair emitted; SQLite gets the
table remade around the new CHECK. One operation, three spellings, and the file reads as one
decision instead of two halves whose order the reader has to reconstruct.

WHY THE RENAME STAYS OUTSIDE IT, which is the load-bearing half of the ordering. A `RebuildTable`
REFUSES a pair of snapshots that disagree about anything but constraints, so it could not swallow the
rename even if that were wanted — and it should not be wanted. A rename hidden inside a rebuild is a
column change with no `RenameColumn` in the file, and `rename_suggestions()` — the tool that made
this decision reviewable in the first place — reads operations, not snapshots. It would go mute on
the very migration that exists to record a rename.

AND THE RENAME NOW GOES FIRST, which reverses the order this file used to carry. The old note said
the CHECK had to be dropped first because "on the engines that name a constraint after its column,
dropping it after the rename would mean naming something that no longer exists" — but this
constraint is named EXPLICITLY, here and in `0001`, so no engine derives its name from a column.
Measured on both engines that own the minimal path: MariaDB rewrites the check clause to the new
column name and keeps the constraint name (`ALTER TABLE ... DROP CONSTRAINT ck_...` after the rename
succeeds), and Postgres does the same. With the rename first, `before` describes the table as it
REALLY stands at that instant — `on_hand` already, the old constraint name still on it — and one
rebuild does the whole swap instead of two.

THE SNAPSHOTS ARE COMPLETE ON PURPOSE. On SQLite the rebuild recreates the table from `after`, so
anything missing from that snapshot is data or structure lost in silence. So both carry every
column, the composite primary key, both foreign keys and the comment — `warehouse_stock` as of
`0002`, with `quantity` already renamed. It has no indexes of its own and no triggers (the one
trigger in the demos hangs off `visits`), and `triggers=()` is therefore the truth rather than an
omission: a rebuild over a table the state knows triggers for refuses to apply.

AND THE VIEW COMES DOWN FIRST, WHICH IS A BUG FIX AND NOT A COURTESY. `low_stock` — created by
`0003` — selects `quantity` from this very table. Measured: after `ALTER TABLE ... RENAME COLUMN`,
MariaDB leaves the view POINTING AT NOTHING — `SELECT * FROM low_stock` answers «references invalid
table(s) or column(s)», error 1356 — because a MySQL view freezes the names it was written with.
Postgres re-points it by itself and SQLite rewrites the stored text, so two engines out of three hid
it, and the demos never noticed because `0005` replaces the view immediately afterwards. A schema
that is broken between two migrations is broken, and a history is applied one migration at a time.
So the view is dropped before the rename and put back after it, saying the SAME thing under the new
name; `0005` then changes the QUESTION it asks, which is that file's own subject.
"""

from __future__ import annotations

import datetime

import snakeorm.times
from snakeorm.expressions import SnakeExpr
from snakeorm.metadata import (
    SnakeCheckInfo,
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeForeignKeyInfo,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeRelationshipInfo,
    SnakeRelationshipKind,
    SnakeTableInfo,
    SnakeTableKind,
)
from snakeorm.migration import (
    CreateView,
    DropView,
    Migration,
    RebuildTable,
    RenameColumn,
    SnakeOperation,
)

version = "0004_on_hand_and_available_view"

_warehouse_id = SnakeColumnInfo(
    name="warehouse_id",
    python_type=int,
    attr_name="warehouse_id",
    type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
)
_sku_id = SnakeColumnInfo(
    name="sku_id",
    python_type=int,
    attr_name="sku_id",
    type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
)
_on_hand = SnakeColumnInfo(
    name="on_hand",
    python_type=int,
    attr_name="on_hand",
    type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
)
_reserved = SnakeColumnInfo(
    name="reserved",
    python_type=int,
    default=0,
    has_default=True,
    attr_name="reserved",
    type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
)
_counted_at = SnakeColumnInfo(
    name="counted_at",
    python_type=snakeorm.times.SnakeUtc,
    nullable=True,
    attr_name="counted_at",
    type_params=SnakeDateTimeParams(tz=True, precision=None),
)
_counted_local = SnakeColumnInfo(
    name="counted_local",
    python_type=datetime.datetime,
    nullable=True,
    attr_name="counted_local",
    type_params=SnakeDateTimeParams(tz=False, precision=None),
)

_relationships = (
    SnakeRelationshipInfo(
        name="warehouse",
        target="Warehouse",
        kind=SnakeRelationshipKind.TO_ONE,
        foreign_key=SnakeForeignKeyInfo(
            target="Warehouse",
            pairs=(("warehouse_id", "id"),),
        ),
        target_table="public.warehouses",
    ),
    SnakeRelationshipInfo(
        name="sku",
        target="Sku",
        kind=SnakeRelationshipKind.TO_ONE,
        foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
        target_table="public.skus",
    ),
    SnakeRelationshipInfo(
        name="movements",
        target="StockMovement",
        kind=SnakeRelationshipKind.TO_MANY,
        foreign_key=SnakeForeignKeyInfo(
            target="Stock",
            pairs=(
                ("stock_warehouse_id", "warehouse_id"),
                ("stock_sku_id", "sku_id"),
            ),
        ),
        target_table="public.stock_movements",
    ),
)

# The condition is an AST and not emitted SQL, which is what keeps a CHECK engine-agnostic: the
# dialect supplies the quoting. Written with a bare `SnakeExpr` rather than through the model,
# because a migration describes the schema AT ITS MOMENT — and here the two conditions are the same
# expression on purpose. Only the NAME changes: the column it guards was called `quantity` when the
# constraint was born and is called `on_hand` by the time this runs, so what is being corrected is a
# name that has started to lie, not the rule it enforces.
_old_check = SnakeCheckInfo(
    condition=SnakeExpr[int](path=("on_hand",)) >= 0,
    name="ck_warehouse_stock_quantity_not_negative",
)
_new_check = SnakeCheckInfo(
    condition=SnakeExpr[int](path=("on_hand",)) >= 0,
    name="ck_warehouse_stock_on_hand_not_negative",
)
_reserved_check = SnakeCheckInfo(
    condition=SnakeExpr[int](path=("reserved",)) >= 0,
    name="ck_warehouse_stock_reserved_not_negative",
)

_columns = (_warehouse_id, _sku_id, _on_hand, _reserved, _counted_at, _counted_local)
_primary_key = SnakePrimaryKeyInfo(columns=(_warehouse_id, _sku_id))

warehouse_stock_before = SnakeTableInfo(
    name="warehouse_stock",
    columns=_columns,
    primary_key=_primary_key,
    relationships=_relationships,
    checks=(_old_check, _reserved_check),
    db_comment="Stock of one SKU in one warehouse",
)
warehouse_stock_after = SnakeTableInfo(
    name="warehouse_stock",
    columns=_columns,
    primary_key=_primary_key,
    relationships=_relationships,
    checks=(_reserved_check, _new_check),
    db_comment="Stock of one SKU in one warehouse",
)

# `low_stock` as `0003` left it and as this migration puts it back: the same question — what is on
# the shelf — asked of a column that has changed name. The body stays unqualified, unquoted and
# lower-case for the reason `0003` writes down at length: that spelling is the intersection of the
# three engines, and a frozen `public.`-qualified SELECT is a plan every checker accepts and SQLite
# then refuses at the server.
#
# `reserved` is spelled out again instead of reusing the table's column: in the table it carries
# `default=0`, and a view column has no default to carry.
low_stock_before = SnakeTableInfo(
    name="low_stock",
    columns=(
        _warehouse_id,
        _sku_id,
        SnakeColumnInfo(
            name="quantity",
            python_type=int,
            attr_name="quantity",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        _counted_at,
        _counted_local,
    ),
    primary_key=SnakePrimaryKeyInfo(columns=()),
    kind=SnakeTableKind.VIEW,
    view_definition=(
        "SELECT warehouse_id, sku_id, quantity, reserved, counted_at, counted_local "
        "FROM warehouse_stock WHERE quantity < 10"
    ),
)

low_stock_renamed = SnakeTableInfo(
    name="low_stock",
    columns=(
        _warehouse_id,
        _sku_id,
        _on_hand,
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        _counted_at,
        _counted_local,
    ),
    primary_key=SnakePrimaryKeyInfo(columns=()),
    kind=SnakeTableKind.VIEW,
    view_definition=(
        "SELECT warehouse_id, sku_id, on_hand, reserved, counted_at, counted_local "
        "FROM warehouse_stock WHERE on_hand < 10"
    ),
)

operations: list[SnakeOperation] = [
    # The view goes down first so that no engine has to carry it across the rename — MariaDB cannot,
    # and on SQLite a view standing over a table that gets REMADE stops the rebuild outright: the
    # `ALTER TABLE ... RENAME TO` that puts the new table in place re-parses the whole schema and
    # finds the view naming a table that is not there yet.
    DropView(low_stock_before),
    # The rename goes next: the constraint carries an explicit name, so no engine loses track of it
    # when the column underneath changes name — which is what lets the snapshot below describe the
    # table with `on_hand` in it and the OLD constraint name still on it, the shape it really has
    # once this line has run. `RenameColumn` reads only the table's NAME off what it is handed, so
    # reusing that snapshot here names the right table and says nothing untrue about the rest.
    RenameColumn(warehouse_stock_before, "quantity", "on_hand"),
    RebuildTable(warehouse_stock_before, warehouse_stock_after, triggers=()),
    CreateView(low_stock_renamed),
]

migration = Migration(version=version, operations=tuple(operations))
