"""Migration generated by SnakeORM. Editable by hand.

The view stops asking what is on the SHELF and starts asking what is AVAILABLE.

`on_hand < 10` flagged a pair holding nine units with nothing reserved, and said nothing about one
holding fifty of which forty-five are promised — five available, and a replenishment dashboard never
heard of it. The right question is `on_hand - reserved`, and it could not be WRITTEN until the ORM
learned to compare a column against a column: before that the right-hand side of a comparison was
always a literal, so the view settled for the question it could express.

The column rename in `0004` is the same change seen from the other side: with `reserved` beside it,
"on_hand" does not say whether the reserved units are inside.

SO `before` HERE SPEAKS OF `on_hand`, NOT OF `quantity`. `0004` takes this view down before renaming
the column and puts it back asking the same question under the new name — it has to, because a
MariaDB view frozen over a renamed column answers error 1356 and because SQLite cannot remake a
table a view is standing on. The state this file receives therefore already says `on_hand`, and a
`before` still spelling `quantity` would be a `down` that recreates a view no engine ever held.

THE NEW SHAPE CARRIES A `view_query`, NOT A FROZEN SELECT, and that is the second edit here.
`makemigrations` wrote the body out the way ONE engine renders it, `public` schema and all, and a
`CreateView` carrying that string is a plan `realize` accepts and the server then rejects — SQLite
says «view "low_stock" cannot reference objects in database public». A `view_query` is the mechanism
`@snake_view(query=...)` already uses for exactly this reason, spelled out in `snake_view`'s own
docstring: the query is stored UNCOMPILED and `view_body` renders it in the TARGET dialect, so the
quoting and the schema qualification are decided at emission time instead of at generation time.

It reads the LIVE model, which a migration normally must not do — a migration is the schema at ITS
moment, and the model is the schema today. Here they are the same schema: this is the LAST word on
`low_stock`, so `Stock` today is `Stock` as of this migration, and `test_migration_drift` is the net
that says so out loud, since it compares this very state against the models. The moment a later
migration moves the view again, that one takes over the responsibility and this file goes back to
being history — which is why `0003`, which is history already, writes its body by hand instead.
"""

from __future__ import annotations

import datetime
import snakeorm.times

from snakeorm import SnakeQuery
from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
    SnakeTableKind,
)
from snakeorm.migration import (
    AlterView,
    Migration,
    SnakeOperation,
)

from shared.models.inventory_models import Stock

version = "0005_low_stock_asks_about_available"

low_stock_before = SnakeTableInfo(
    name="low_stock",
    columns=(
        SnakeColumnInfo(
            name="warehouse_id",
            python_type=int,
            attr_name="warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="sku_id",
            python_type=int,
            attr_name="sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="on_hand",
            python_type=int,
            attr_name="on_hand",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="counted_at",
            python_type=snakeorm.times.SnakeUtc,
            nullable=True,
            attr_name="counted_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="counted_local",
            python_type=datetime.datetime,
            nullable=True,
            attr_name="counted_local",
            type_params=SnakeDateTimeParams(tz=False, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(columns=()),
    kind=SnakeTableKind.VIEW,
    view_definition="SELECT warehouse_id, sku_id, on_hand, reserved, counted_at, counted_local FROM warehouse_stock WHERE on_hand < 10",
)

low_stock_after = SnakeTableInfo(
    name="low_stock",
    columns=(
        SnakeColumnInfo(
            name="warehouse_id",
            python_type=int,
            attr_name="warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="sku_id",
            python_type=int,
            attr_name="sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="on_hand",
            python_type=int,
            attr_name="on_hand",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reserved",
            python_type=int,
            attr_name="reserved",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="counted_at",
            python_type=snakeorm.times.SnakeUtc,
            nullable=True,
            attr_name="counted_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="counted_local",
            python_type=datetime.datetime,
            nullable=True,
            attr_name="counted_local",
            type_params=SnakeDateTimeParams(tz=False, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(columns=()),
    kind=SnakeTableKind.VIEW,
    view_query=SnakeQuery(Stock).filter(Stock.on_hand - Stock.reserved < 10),
)

operations: list[SnakeOperation] = [
    AlterView(low_stock_before, low_stock_after),
]

migration = Migration(version=version, operations=tuple(operations))
