"""Migration generated by SnakeORM. Editable by hand.

The movements gain a READ MODEL WITH NO IDENTITY, which is the one thing a table cannot be.

`stock_movements` is a table of entities: every projection of it carries `id`, because the ORM
refuses to build a row that could not be written back — `only()` puts the key in whether it was
named or not, and `defer()` says so out loud when asked to leave it. So two receipts of one unit,
identical in every column a book prints, are never the same answer twice.

A ledger line is not an entity. `stock_ledger` is the same rows read as FACTS: read-only, no primary
key, and `defer(StockLedger.id)` therefore allowed. That is what lets the movement book join its two
origins with `UNION ALL` and mean it — a `UNION` over lines with no identity folds two events into
one and leaves the book disagreeing with the stock.

WRITTEN BY HAND, and it has to be: `makemigrations --only` collects by `__snake_registry__`, which a
`SnakeView` does not carry, so no generator emits a `CreateView`.

IT CARRIES A `view_query` AND NOT A FROZEN SELECT, for the reason `0005` sets out at length: a body
rendered by one engine — `public` schema and all — is a plan `realize` accepts and the server then
rejects. `view_body` renders the query in the TARGET dialect at emission time, so the same migration
applies on the three engines. It reads the live model because this is the FIRST and LAST word on
`stock_ledger`; `test_migration_drift` is the net that says the two agree.
"""

from __future__ import annotations

import snakeorm.times

from snakeorm import SnakeQuery
from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeStrParams,
    SnakeTableInfo,
    SnakeTableKind,
)
from snakeorm.migration import (
    CreateView,
    Migration,
    SnakeOperation,
)

from shared.models.inventory_models import MovementReason, StockMovement

version = "0006_stock_ledger_view"

stock_ledger = SnakeTableInfo(
    name="stock_ledger",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="stock_warehouse_id",
            python_type=int,
            attr_name="stock_warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="stock_sku_id",
            python_type=int,
            attr_name="stock_sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="delta",
            python_type=int,
            attr_name="delta",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reason",
            python_type=MovementReason,
            attr_name="reason",
            type_params=SnakeStrParams(max_length=10, fixed=False),
            enum_type=MovementReason,
        ),
        SnakeColumnInfo(
            name="note",
            python_type=str,
            nullable=True,
            attr_name="note",
            type_params=SnakeStrParams(max_length=200, fixed=False),
        ),
        SnakeColumnInfo(
            name="happened_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="happened_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(columns=()),
    kind=SnakeTableKind.VIEW,
    view_query=SnakeQuery(StockMovement),
)

operations: list[SnakeOperation] = [
    CreateView(stock_ledger),
]

migration = Migration(version=version, operations=tuple(operations))
