"""A mirror has to name the table it actually read, and say the same thing about NULL that it does.

Three failures that share a shape: the generated file looked right and was wrong.

The first is the worst thing this ORM can do. `render_models` never emitted `schema=`, which
defaults to `public`, so mirroring `sales.orders` produced a class called `SalesOrders` sitting on
top of `@snake_db_first(table="orders")` — reading `public.orders`. Two halves of the same
declaration contradicting each other, in silence, and the generator KNEW the schema: it uses it to
build the class name.

The second does not run at all, which is the only mercy in it: the linker demands a to-one say the
same thing as its foreign key about possibly not existing, and the generator never looked at
`nullable`. One relationship out of parity is enough to stop the whole file importing.

The third is a sentence. The header promised that changing `@snake_db_first` to `@snake_model`
ADOPTS the table, and it does not — the decorator's own docstring says the autogenerated
`CreateTable` dies with `DuplicateTable`. It is the copy the reader has in front of them.
"""

from __future__ import annotations

import importlib
import sys
from collections.abc import Iterator

import pytest

from snakeorm.core.placement import DEFAULT_SCHEMA
from snakeorm.introspection.models import render_models
from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipInfo,
    SnakeRelationshipKind,
    SnakeTableInfo,
)
from snakeorm.registry import registry

_ID = SnakeColumnInfo(name="id", python_type=int, attr_name="id")


def _parent(schema: str = DEFAULT_SCHEMA) -> SnakeTableInfo:
    """The table a foreign key points at."""
    return SnakeTableInfo(
        name="marques",
        schema=schema,
        columns=(_ID,),
        primary_key=SnakePrimaryKeyInfo(columns=(_ID,)),
    )


def _child(*, nullable: bool, schema: str = DEFAULT_SCHEMA) -> SnakeTableInfo:
    """A table with one foreign key, whose column accepts NULL or does not."""
    fk_column = SnakeColumnInfo(
        name="marque_id", python_type=int, attr_name="marque_id", nullable=nullable
    )
    return SnakeTableInfo(
        name="wagons",
        schema=schema,
        columns=(_ID, fk_column),
        primary_key=SnakePrimaryKeyInfo(columns=(_ID,)),
        relationships=(
            SnakeRelationshipInfo(
                name="marques",
                target="marques",
                kind=SnakeRelationshipKind.TO_ONE,
                foreign_key=SnakeForeignKeyInfo(
                    target="marques", pairs=(("marque_id", "id"),)
                ),
            ),
        ),
    )


def test_a_table_outside_public_carries_its_schema() -> None:
    """`sales.orders` mirrors `sales.orders`, not `public.orders`.

    The class name already said `sales`; the decorator said nothing, so it read the default. A
    database with the same table name in two schemas served the wrong rows and nothing complained.
    """
    rendered = render_models([_parent(schema="sales")])

    assert '@snake_db_first(table="marques", schema="sales")' in rendered


def test_a_table_in_the_default_schema_says_nothing_about_it() -> None:
    """Emitting nothing and emitting `schema="public"` MEAN the same, so the quiet one wins.

    It is not a special case: the decorator's default IS `DEFAULT_SCHEMA`. What would be noise in
    every ordinary file is left out, and the bug above is impossible either way.
    """
    rendered = render_models([_parent()])

    assert "schema=" not in rendered


def test_a_cross_schema_class_name_and_its_table_agree() -> None:
    """The two halves of the declaration name the same table, whatever the naming switches do."""
    rendered = render_models([_parent(schema="sales")])

    assert "class SalesMarques(SnakeModel):" in rendered
    assert 'table="marques", schema="sales"' in rendered


@pytest.mark.parametrize(
    ("nullable", "expected"),
    [(True, "SnakeToOne[PublicMarques | None]"), (False, "SnakeToOne[PublicMarques]")],
)
def test_a_to_one_says_what_its_foreign_key_says_about_null(
    nullable: bool, expected: str
) -> None:
    """`| None` iff the key accepts NULL — which is the linker's rule, not a preference.

    Both directions, because the guard demands both: an optional relationship over a `NOT NULL`
    key forces an impossible case to be handled.
    """
    rendered = render_models([_child(nullable=nullable), _parent()], names=None)

    assert expected in rendered


def test_a_composite_key_is_optional_when_any_member_accepts_null() -> None:
    """One nullable member is enough: a key with a NULL in it matches no row at all."""
    columns = (
        _ID,
        SnakeColumnInfo(name="wh_id", python_type=int, attr_name="wh_id"),
        SnakeColumnInfo(
            name="wh_sku", python_type=int, attr_name="wh_sku", nullable=True
        ),
    )
    child = SnakeTableInfo(
        name="wagons",
        columns=columns,
        primary_key=SnakePrimaryKeyInfo(columns=(_ID,)),
        relationships=(
            SnakeRelationshipInfo(
                name="marques",
                target="marques",
                kind=SnakeRelationshipKind.TO_ONE,
                foreign_key=SnakeForeignKeyInfo(
                    target="marques", pairs=(("wh_id", "id"), ("wh_sku", "id"))
                ),
            ),
        ),
    )

    assert "SnakeToOne[PublicMarques | None]" in render_models([child, _parent()])


@pytest.fixture(scope="module")
def linked_mirror(tmp_path_factory: pytest.TempPathFactory) -> Iterator[object]:
    """Writes a mirror with a NULLABLE foreign key, IMPORTS it and LINKS it for real.

    The only place the parity guard runs. Comparing strings would have passed on the broken
    version: it is `snake_link()` that refuses, and nothing before it.
    """
    dest = tmp_path_factory.mktemp("mirror_nullable")
    (dest / "mirror_nullable.py").write_text(
        render_models([_child(nullable=True), _parent()]), encoding="utf-8"
    )
    sys.path.insert(0, str(dest))
    try:
        yield importlib.import_module("mirror_nullable")
    finally:
        sys.path.remove(str(dest))


def test_a_mirror_with_a_nullable_foreign_key_imports_and_links(
    linked_mirror: object,
) -> None:
    """The whole point: the file RUNS. Importing it fires the decorator and `snake_link()`."""
    model = getattr(linked_mirror, "PublicWagons")

    table = registry.table_of(model)
    assert table is not None
    assert [
        relationship.name
        for relationship in table.relationships
        if relationship.kind is SnakeRelationshipKind.TO_ONE
    ] == ["marque"]


def test_the_header_does_not_promise_adoption_by_changing_one_line() -> None:
    """The claim was false in four places; this is the one shipped inside the file itself.

    `@snake_db_first` -> `@snake_model` does not hand the table to migrations: the history has
    never seen it, so the autogen emits a `CreateTable` that dies with `DuplicateTable`.
    """
    rendered = render_models([_parent()])

    assert "To ADOPT a table" not in rendered
    assert "DuplicateTable" in rendered


def test_the_header_says_what_a_mirror_cannot_carry() -> None:
    """A database is a LOSSY projection of the code, and the file has to say so.

    Signals, `default_factory`, the `StrEnum` class, methods and constants live in a `.py` — often
    in another repository — and no row of the catalogue mentions them. Silence here reads as
    "everything is covered", which is the one thing this generator must never imply.
    """
    rendered = render_models([_parent()])

    assert "default_factory" in rendered
    assert "Signals" in rendered
