"""Three things the introspector hands over and the generator was dropping on the floor.

Not a limitation and not a missing query: `SnakeTableInfo` arrived with `autoincrement` on its
columns, an `indexes` tuple and a `db_comment`, and `render_models` walked past all three. Measured
against the demo database — 27 autoincrement columns, 33 indexes and 8 table comments read, and
zero of any of them in the generated file.

Each one costs something different when it is missing. An autoincrement PK mirrored as
`snake_int(primary_key=True)` puts `id` back in the constructor, so the mirror asks for a value the
database generates. A dropped index is invisible until somebody diffs the mirror against the schema
and is told to create what already exists. And the comment is often the only thing that says what a
table inherited as `t_cst_rel_04` is FOR.
"""

from __future__ import annotations

import importlib
import sys
from collections.abc import Iterator

import pytest

from snakeorm.expressions import SnakeExpr
from snakeorm.introspection.models import render_models, unrepresentable
from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeIndexInfo,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
)
from snakeorm.registry import registry


def _table(
    *columns: SnakeColumnInfo,
    indexes: tuple[SnakeIndexInfo, ...] = (),
    db_comment: str | None = None,
) -> SnakeTableInfo:
    """A table whose first column is the primary key."""
    return SnakeTableInfo(
        name="fleet",
        columns=columns,
        primary_key=SnakePrimaryKeyInfo(columns=(columns[0],)),
        indexes=indexes,
        db_comment=db_comment,
    )


def _pk(
    *, autoincrement: bool, int_size: SnakeIntSize = SnakeIntSize.BIGINT
) -> SnakeColumnInfo:
    """The primary key column, generated by the database or not."""
    return SnakeColumnInfo(
        name="id",
        python_type=int,
        attr_name="id",
        autoincrement=autoincrement,
        type_params=SnakeIntParams(size=int_size),
    )


def test_a_database_generated_key_becomes_snake_auto() -> None:
    """`nextval(...)` on the PK is `snake_auto()`, which is what keeps `id` out of `__init__`."""
    rendered = render_models([_table(_pk(autoincrement=True))])

    imported = next(
        line
        for line in rendered.splitlines()
        if line.startswith("from snakeorm import")
    )

    assert "id: SnakeColumn[int] = snake_auto()" in rendered
    assert "snake_auto" in imported


def test_a_key_the_client_supplies_is_not_snake_auto() -> None:
    """A PK with no `nextval` is an ordinary column, and saying otherwise would invent a sequence."""
    rendered = render_models([_table(_pk(autoincrement=False))])

    assert "snake_auto" not in rendered
    assert "id: SnakeColumn[int] = snake_int(primary_key=True)" in rendered


def test_snake_auto_carries_the_width_the_column_really_has() -> None:
    """A `SERIAL` is not a `BIGSERIAL`, and `snake_auto` spells the knob `int_size=`, not `size=`."""
    rendered = render_models(
        [_table(_pk(autoincrement=True, int_size=SnakeIntSize.INTEGER))]
    )

    assert "snake_auto(int_size=SnakeIntSize.INTEGER)" in rendered


def test_the_indexes_the_introspector_read_are_declared() -> None:
    """A `SnakeIndexes` block in the body, referencing the descriptors above it by name.

    The names resolve at COMPILE time —after `__set_name__`— so a bare `brand_id` inside the body
    is the descriptor and works, which is how a hand-written model declares it too.
    """
    rendered = render_models(
        [
            _table(
                _pk(autoincrement=True),
                SnakeColumnInfo(name="brand_id", python_type=int, attr_name="brand_id"),
                indexes=(
                    SnakeIndexInfo(columns=("brand_id",), name="ix_fleet_brand_id"),
                ),
            )
        ]
    )

    assert "    SnakeIndexes = [" in rendered
    assert "SnakeIndex(brand_id)" in rendered


def test_an_index_whose_name_the_database_chose_keeps_it() -> None:
    """A name the generator would not have produced is DATA, so it travels.

    `resolved_name` invents `ix_<table>_<columns>` when none is given, so emitting that one back
    would be noise. Anything else is a name somebody set, and dropping it makes a drift report
    claim the index is missing.
    """
    rendered = render_models(
        [
            _table(
                _pk(autoincrement=True),
                SnakeColumnInfo(name="brand_id", python_type=int, attr_name="brand_id"),
                indexes=(SnakeIndexInfo(columns=("brand_id",), name="legacy_idx_04"),),
            )
        ]
    )

    assert 'SnakeIndex(brand_id, name="legacy_idx_04")' in rendered


def test_a_table_with_no_indexes_leaves_no_dead_import() -> None:
    """Ruff runs over the generated file too, and an unused import is an error there."""
    rendered = render_models([_table(_pk(autoincrement=True))])

    assert "SnakeIndex" not in rendered


def test_a_table_comment_travels_as_snake_comment() -> None:
    """The compiler reads `SnakeComment` off the class body — no decorator parameter needed.

    Often the only thing that says what an inherited table is for, and the introspector was already
    reading it on all three engines.
    """
    rendered = render_models(
        [_table(_pk(autoincrement=True), db_comment="Fleet of cars")]
    )

    assert 'SnakeComment = "Fleet of cars"' in rendered


def test_a_partial_index_is_left_out_and_SAID() -> None:
    """The one index the generator cannot write, and the reason it must not go quiet about it.

    `where` is a `SnakeCondition`, and rendering one back to source is an expression printer this
    does not have. Dropping it in silence sends the reader to diff the mirror and be told to
    create an index that already exists.
    """
    table = _table(
        _pk(autoincrement=True),
        SnakeColumnInfo(
            name="deleted_at", python_type=int, attr_name="deleted_at", nullable=True
        ),
        indexes=(
            SnakeIndexInfo(
                columns=("deleted_at",),
                name="ix_live",
                where=SnakeExpr[int](path=("deleted_at",)) == 0,
            ),
        ),
    )

    rendered = render_models([table])

    assert "SnakeIndexes" not in rendered
    assert any("is PARTIAL" in complaint for complaint in unrepresentable([table]))
    assert "ix_live" in rendered


@pytest.fixture(scope="module")
def mirrored(tmp_path_factory: pytest.TempPathFactory) -> Iterator[object]:
    """Writes the mirror of a table carrying all three, IMPORTS it and returns the model."""
    table = _table(
        _pk(autoincrement=True, int_size=SnakeIntSize.INTEGER),
        SnakeColumnInfo(name="brand_id", python_type=int, attr_name="brand_id"),
        indexes=(SnakeIndexInfo(columns=("brand_id",), name="legacy_idx_04"),),
        db_comment="Fleet of cars",
    )
    dest = tmp_path_factory.mktemp("mirror_knobs")
    (dest / "mirror_knobs.py").write_text(render_models([table]), encoding="utf-8")
    sys.path.insert(0, str(dest))
    try:
        module = importlib.import_module("mirror_knobs")
        yield getattr(module, "PublicFleet")
    finally:
        sys.path.remove(str(dest))


def test_the_three_survive_the_round_trip(mirrored: type) -> None:
    """The file RUNS and the compiled graph holds what the database said.

    Comparing strings proves the generator wrote something; only importing proves the compiler
    accepts it. That gap is where `snake_auto(size=)` would have lived — the knob is `int_size=`.
    """
    compiled = registry.table_of(mirrored)

    assert compiled is not None
    assert compiled.db_comment == "Fleet of cars"
    assert [index.name for index in compiled.indexes] == ["legacy_idx_04"]
    identifier = compiled.get_column("id")
    assert identifier is not None
    assert identifier.autoincrement is True
    assert identifier.int_size is SnakeIntSize.INTEGER


def test_a_generated_key_is_not_asked_for_in_the_constructor(mirrored: type) -> None:
    """What `snake_auto` is FOR: the database supplies the id, so the caller must not.

    With `snake_int(primary_key=True)` the mirror demanded an `id` that does not exist yet, which
    is the visible half of the bug — the rest is the type checker approving the wrong call.
    """
    instance = mirrored(brand_id=7)

    assert instance.brand_id == 7
