"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import snakeorm.times


from snakeorm.metadata import (
    SnakeDateTimeParams,
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeTableInfo,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_billing_initial"

invoices = SnakeTableInfo(
    name="invoices",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="amount_cents", python_type=int, attr_name="amount_cents"),
        SnakeColumnInfo(
            name="paid",
            python_type=bool,
            default=False,
            has_default=True,
            attr_name="paid",
        ),
        SnakeColumnInfo(
            name="subscription_id",
            python_type=int,
            index=True,
            attr_name="subscription_id",
        ),
        SnakeColumnInfo(
            name="issued_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="issued_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="subscription",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Subscription",
                pairs=(("subscription_id", "id"),),
            ),
            target_table="public.subscriptions",
        ),
        SnakeRelationshipInfo(
            name="payments",
            target="Payment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.payments",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("subscription_id",)),),
)

payments = SnakeTableInfo(
    name="payments",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="amount_cents", python_type=int, attr_name="amount_cents"),
        SnakeColumnInfo(name="method", python_type=str, attr_name="method"),
        SnakeColumnInfo(
            name="invoice_id",
            python_type=int,
            index=True,
            attr_name="invoice_id",
        ),
        SnakeColumnInfo(
            name="paid_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="paid_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="invoice",
            target="Invoice",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.invoices",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("invoice_id",)),),
)

plans = SnakeTableInfo(
    name="plans",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="name", python_type=str, unique=True, attr_name="name"),
        SnakeColumnInfo(name="price_cents", python_type=int, attr_name="price_cents"),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="subscriptions",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Plan", pairs=(("plan_id", "id"),)),
            target_table="public.subscriptions",
        ),
    ),
)

subscriptions = SnakeTableInfo(
    name="subscriptions",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="active",
            python_type=bool,
            default=True,
            has_default=True,
            attr_name="active",
        ),
        SnakeColumnInfo(
            name="user_id",
            python_type=int,
            index=True,
            attr_name="user_id",
        ),
        SnakeColumnInfo(
            name="plan_id",
            python_type=int,
            index=True,
            attr_name="plan_id",
        ),
        SnakeColumnInfo(
            name="started_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="started_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        SnakeRelationshipInfo(
            name="plan",
            target="Plan",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Plan", pairs=(("plan_id", "id"),)),
            target_table="public.plans",
        ),
        SnakeRelationshipInfo(
            name="invoices",
            target="Invoice",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Subscription",
                pairs=(("subscription_id", "id"),),
            ),
            target_table="public.invoices",
        ),
    ),
    indexes=(
        SnakeIndexInfo(columns=("user_id",)),
        SnakeIndexInfo(columns=("plan_id",)),
    ),
)

users = SnakeTableInfo(
    name="users",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="username",
            python_type=str,
            unique=True,
            attr_name="username",
        ),
        SnakeColumnInfo(name="email", python_type=str, unique=True, attr_name="email"),
        SnakeColumnInfo(
            name="password_hash",
            python_type=str,
            attr_name="password_hash",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="roles",
            target="Role",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.roles",
        ),
        SnakeRelationshipInfo(
            name="api_tokens",
            target="ApiToken",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.api_tokens",
        ),
        SnakeRelationshipInfo(
            name="sessions",
            target="LoginSession",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.login_sessions",
        ),
        SnakeRelationshipInfo(
            name="blogs",
            target="Blog",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("owner_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="posts",
            target="Post",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="subscriptions",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.subscriptions",
        ),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(invoices),
    CreateTable(payments),
    CreateTable(plans),
    CreateTable(subscriptions),
    AddForeignKey(
        invoices,
        SnakeRelationshipInfo(
            name="subscription",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Subscription",
                pairs=(("subscription_id", "id"),),
            ),
            target_table="public.subscriptions",
        ),
        subscriptions,
    ),
    AddForeignKey(
        payments,
        SnakeRelationshipInfo(
            name="invoice",
            target="Invoice",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.invoices",
        ),
        invoices,
    ),
    AddForeignKey(
        subscriptions,
        SnakeRelationshipInfo(
            name="plan",
            target="Plan",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Plan", pairs=(("plan_id", "id"),)),
            target_table="public.plans",
        ),
        plans,
    ),
    AddForeignKey(
        subscriptions,
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        users,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
