"""Migration generated by SnakeORM. Editable by hand.

`payments.method` stops being a `str` somebody writes and becomes the DISCRIMINATOR of a hierarchy:
`CardPayment`, `TransferPayment`, `PaypalPayment` and `WalletPayment` share the one table, and each
kind brings the columns that are its own.

Nothing about the existing rows changes. `method` already held exactly those four words — that is the
point, the column was a discriminator that nobody was in charge of — so the four new columns arrive
NULL, which is what a payment that never recorded its brand or its reference holds.

The INDEX is not decoration: every read of a subclass carries `WHERE method = ?`, so without it
finding the cards means scanning every payment there has ever been.
"""

from __future__ import annotations

from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeStrParams,
    SnakeTableInfo,
)
from snakeorm.migration import AddColumn, CreateIndex, Migration, SnakeOperation

version = "0002_payment_kinds"

_id = SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True)

payments = SnakeTableInfo(
    name="payments",
    columns=(_id,),
    primary_key=SnakePrimaryKeyInfo(columns=(_id,)),
)


def _kind_column(name: str, length: int) -> SnakeColumnInfo:
    """A column belonging to ONE kind: nullable, because the other kinds share the row.

    The length travels inside `SnakeStrParams` and not as a loose `max_length`, which is the ORM's
    rule and not a formality: loose, a column could declare `max_length` AND `precision` at once —
    a state no engine represents, living in the graph that IS the truth.

    `has_default=True` alongside `default=None` is not redundant either: nullable says the COLUMN
    accepts NULL, the default says the ARGUMENT is optional. They are two facts and the drift check
    compares both — a card paid at a terminal that does not report its brand is a card all the same.
    """
    return SnakeColumnInfo(
        name=name,
        python_type=str,
        attr_name=name,
        nullable=True,
        default=None,
        has_default=True,
        type_params=SnakeStrParams(max_length=length),
    )


operations: list[SnakeOperation] = [
    AddColumn(payments, _kind_column("card_last4", 4)),
    AddColumn(payments, _kind_column("card_brand", 20)),
    AddColumn(payments, _kind_column("reference", 40)),
    AddColumn(payments, _kind_column("paypal_account", 120)),
    CreateIndex(payments, SnakeIndexInfo(columns=("method",))),
]

migration = Migration(version=version, operations=tuple(operations))
