"""PyMySQLDriver: runs SQL against MySQL/MariaDB with PyMySQL (synchronous). PyMySQL (pure Python) so
no C toolchain is required; whoever wants `mysqlclient` plugs it in here without touching the dialect
(same `%s`). A THIN adapter like `PsycopgDriver`: it only runs the compiled `(sql, params)`.
"""

from __future__ import annotations

from collections.abc import Iterator, Sequence
from typing import Any, Protocol, cast

from snakeorm.drivers.failures import translating
from snakeorm.drivers.savepoints import quote_savepoint

from snakeorm.sql.adapt import adapt_params

_QUOTE = "`"
"""The character THIS engine quotes an identifier with.

MySQL and MariaDB reject a double-quoted identifier unless `ANSI_QUOTES` is on, so a shared helper
that always wrote a double quote turned every `SAVEPOINT` into `ERROR 1064` here. The RULE about
what a valid name is, is shared; the quoting character is the engine's own grammar.
"""


class _Cursor(Protocol):
    """The minimal DBAPI cursor the driver needs."""

    @property
    def rowcount(self) -> int: ...
    @property
    def lastrowid(self) -> int: ...
    @translating
    # `| None` is how these two libraries spell NO PARAMETERS, and it is not the same as an
    # empty sequence: given `()` they re-read the SQL as a format template, so a literal `%` —
    # every DDL statement the migration runner emits — dies before reaching the server. The
    # Protocol has to admit it or the drivers cannot say it.
    def execute(self, sql: str, params: Sequence[object] | None) -> object: ...
    # `Sequence` and not `list`, because PyMySQL hands back a TUPLE of tuples. Declaring `list`
    # here was a claim about somebody else's library that nothing ever measured, and mypy believed
    # it: `fetch_all` promised a list and returned a tuple on this engine alone.
    def fetchall(self) -> Sequence[tuple[object, ...]]: ...
    def fetchmany(self, size: int) -> Sequence[tuple[object, ...]]: ...
    def close(self) -> None: ...


class _Connection(Protocol):
    """The minimal DBAPI connection the driver needs."""

    def cursor(self, cursor_class: object = ...) -> _Cursor: ...
    @translating
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...


class PyMySQLDriver:
    """Synchronous driver over PyMySQL. Implements the SnakeDriver Protocol."""

    def __init__(self, connection: _Connection) -> None:
        self._connection = connection
        self._last_insert_id = 0  # the id generated by the last INSERT (MySQL has no RETURNING; MariaDB does)

    def server_version(self) -> str:
        """What the server calls itself: `11.8.8-MariaDB-ubu2404`, `8.0.46`.

        Empty if it does not answer: a flavour read wrong is worse than none.
        """
        try:
            cursor = self._connection.cursor()
            cursor.execute("SELECT VERSION()", ())
            rows = cursor.fetchall()
            return str(rows[0][0]) if rows else ""
        except Exception:
            return ""

    @classmethod
    def adopt(cls, connection: object) -> PyMySQLDriver:
        """Wraps a raw PyMySQL connection, adapting it to our minimal DBAPI (the edge)."""
        return cls(cast("_Connection", connection))

    @classmethod
    def connect(cls, **kwargs: Any) -> PyMySQLDriver:
        """Opens a PyMySQL connection with the given kwargs (host, user, password, database, port...).
        MySQL uses arguments, not a one-piece DSN. Lazy import: whoever only generates SQL does not need PyMySQL.
        """
        import pymysql

        return cls.adopt(pymysql.connect(**kwargs))

    @translating
    def fetch_all(self, sql: str, params: Sequence[object]) -> list[tuple[object, ...]]:
        """Runs a query and returns all of its rows, closing the cursor."""
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                sql, adapt_params(params, native_arrays=False, percent_formatting=True)
            )
            # `list(...)` and not the cursor's own answer: the Protocol promises a list and PyMySQL
            # gives a tuple. Everything downstream only iterates, so it went unnoticed — until
            # somebody compared the result to one.
            return list(cursor.fetchall())
        finally:
            cursor.close()

    def fetch_iter(
        self, sql: str, params: Sequence[object], *, chunk: int = 1000
    ) -> Iterator[tuple[object, ...]]:
        """Yields the rows in chunks using PyMySQL's UNBUFFERED cursor (`SSCursor`).

        `SSCursor` is the MySQL equivalent of Postgres's named cursor: the result stays on the
        server and arrives on demand. With the normal cursor, PyMySQL pulls EVERYTHING to the
        client on execute, and `fetchmany` would only be slicing a list that is already fully in
        memory.

        Its price, and you have to know it: while the unbuffered cursor is alive, that connection
        cannot fire another query. That is why the cursor is closed once the iteration runs out.
        """
        import pymysql.cursors

        cursor = self._connection.cursor(pymysql.cursors.SSCursor)
        try:
            cursor.execute(
                sql, adapt_params(params, native_arrays=False, percent_formatting=True)
            )
            while True:
                rows = cursor.fetchmany(chunk)
                if not rows:
                    return
                yield from rows
        finally:
            cursor.close()

    @translating
    def execute(self, sql: str, params: Sequence[object]) -> int:
        """Runs a statement fetching no rows and returns the rowcount.
        It stores `lastrowid` (read BEFORE closing the cursor): on MySQL, which has no RETURNING, that is the only way to recover the generated PK.
        """
        cursor = self._connection.cursor()
        try:
            cursor.execute(
                sql, adapt_params(params, native_arrays=False, percent_formatting=True)
            )
            self._last_insert_id = cursor.lastrowid
            return cursor.rowcount
        finally:
            cursor.close()

    @property
    def last_insert_id(self) -> int:
        """The autoincrement id of the last INSERT. The session uses it where there is no RETURNING."""
        return self._last_insert_id

    @translating
    def commit(self) -> None:
        """Commits the transaction in progress."""
        self._connection.commit()

    def rollback(self) -> None:
        """Rolls back the transaction in progress."""
        self._connection.rollback()

    def savepoint(self, name: str) -> None:
        """Emits `SAVEPOINT \\`n\\``. MySQL supports savepoints; the name is quoted with backticks."""
        self.execute(f"SAVEPOINT {quote_savepoint(name, quote=_QUOTE)}", ())

    def release_savepoint(self, name: str) -> None:
        """Emits `RELEASE SAVEPOINT \\`n\\``."""
        self.execute(f"RELEASE SAVEPOINT {quote_savepoint(name, quote=_QUOTE)}", ())

    def rollback_to_savepoint(self, name: str) -> None:
        """Emits `ROLLBACK TO SAVEPOINT \\`n\\``."""
        self.execute(f"ROLLBACK TO SAVEPOINT {quote_savepoint(name, quote=_QUOTE)}", ())

    def close(self) -> None:
        """Closes the connection."""
        self._connection.close()
