"""How a savepoint NAME is written, once, for every driver.

What is shared is the RULE — what counts as a valid name — and NOT the quoting character. MySQL and
MariaDB reject a double-quoted identifier unless `ANSI_QUOTES` is on, so `SAVEPOINT "sp1"` comes
back as `ERROR 1064` — measured, not reasoned about. The quote is engine grammar; the rule is not.
Each driver answers with its own character and there is no default, for the same reason
`adapt_params` has none: a new driver has to DECIDE.

The names the ORM itself generates come from `SnakeSession.savepoint` (`f"sp{depth}"`), so no
caller-supplied name reaches here through the public API.

It lives with the DRIVERS and not with the dialects, even though it is grammar. A driver has no
dialect and never has had — `TimeoutDriver` receives one as a call argument for exactly that reason —
so putting it there would mean handing every driver a dialect to write one pair of quotes.
"""

from __future__ import annotations

import re

_PLAIN = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
"""A plain ASCII identifier, which is all the ORM ever generates.

Stricter than the `isalnum()` two of the four copies used, and deliberately: a name starting with a
digit and a non-ASCII one both pass that check and neither is something this ORM produces.
"""


def quote_savepoint(name: str, *, quote: str) -> str:
    """The name, quoted for a `SAVEPOINT` statement with THIS engine's character, or a refusal.

    It REFUSES rather than escaping, and that is the decision. The name is always generated by the
    session, so anything that is not a plain identifier is a bug in whoever called — and escaping a
    bug is how it ends up written into the database instead of reported.

    `quote` is keyword-only and has no default: a driver has to say which character its engine
    accepts. A default of `"` looked harmless and is what broke MySQL, where an identifier in double
    quotes is a syntax error unless `ANSI_QUOTES` is set.
    """
    if not _PLAIN.match(name):
        raise ValueError(
            f"Invalid savepoint name: {name!r}. The ORM generates these itself, so a name it does "
            f"not recognise means somebody called the driver directly with one of their own. It "
            f"must be a plain ASCII identifier."
        )
    return f"{quote}{name}{quote}"
