"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import snakeorm.times

import shared.models.blog_models

from snakeorm.metadata import (
    SnakeDateTimeParams,
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeTableInfo,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_engagement_initial"

comments = SnakeTableInfo(
    name="comments",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="body", python_type=str, attr_name="body"),
        SnakeColumnInfo(
            name="post_id",
            python_type=int,
            index=True,
            attr_name="post_id",
        ),
        SnakeColumnInfo(
            name="author_id",
            python_type=int,
            index=True,
            attr_name="author_id",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="author",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.users",
        ),
    ),
    indexes=(
        SnakeIndexInfo(columns=("post_id",)),
        SnakeIndexInfo(columns=("author_id",)),
    ),
)

reactions = SnakeTableInfo(
    name="reactions",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="kind", python_type=str, attr_name="kind"),
        SnakeColumnInfo(
            name="post_id",
            python_type=int,
            index=True,
            attr_name="post_id",
        ),
        SnakeColumnInfo(
            name="user_id",
            python_type=int,
            index=True,
            attr_name="user_id",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
    ),
    indexes=(
        SnakeIndexInfo(columns=("post_id",)),
        SnakeIndexInfo(columns=("user_id",)),
    ),
)

visits = SnakeTableInfo(
    name="visits",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="post_id",
            python_type=int,
            index=True,
            attr_name="post_id",
        ),
        SnakeColumnInfo(name="ip", python_type=str, attr_name="ip"),
        SnakeColumnInfo(
            name="user_agent",
            python_type=str,
            nullable=True,
            attr_name="user_agent",
        ),
        SnakeColumnInfo(
            name="visited_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="visited_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("post_id",)),),
)

users = SnakeTableInfo(
    name="users",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="username",
            python_type=str,
            unique=True,
            attr_name="username",
        ),
        SnakeColumnInfo(name="email", python_type=str, unique=True, attr_name="email"),
        SnakeColumnInfo(
            name="password_hash",
            python_type=str,
            attr_name="password_hash",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="roles",
            target="Role",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.roles",
        ),
        SnakeRelationshipInfo(
            name="api_tokens",
            target="ApiToken",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.api_tokens",
        ),
        SnakeRelationshipInfo(
            name="sessions",
            target="LoginSession",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.login_sessions",
        ),
        SnakeRelationshipInfo(
            name="blogs",
            target="Blog",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("owner_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="posts",
            target="Post",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="subscriptions",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.subscriptions",
        ),
    ),
)

posts = SnakeTableInfo(
    name="posts",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="title", python_type=str, attr_name="title"),
        SnakeColumnInfo(name="body", python_type=str, attr_name="body"),
        SnakeColumnInfo(
            name="published",
            python_type=bool,
            default=False,
            has_default=True,
            attr_name="published",
        ),
        SnakeColumnInfo(
            name="blog_id",
            python_type=int,
            index=True,
            attr_name="blog_id",
        ),
        SnakeColumnInfo(
            name="category_id",
            python_type=int,
            nullable=True,
            index=True,
            attr_name="category_id",
        ),
        SnakeColumnInfo(
            name="author_id",
            python_type=int,
            index=True,
            attr_name="author_id",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            default_factory=shared.models.blog_models.utcnow,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="blog",
            target="Blog",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Blog", pairs=(("blog_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="category",
            target="Category",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Category",
                pairs=(("category_id", "id"),),
            ),
            target_table="public.categories",
        ),
        SnakeRelationshipInfo(
            name="author",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.users",
        ),
        SnakeRelationshipInfo(
            name="revisions",
            target="PostRevision",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.post_revisions",
        ),
        SnakeRelationshipInfo(
            name="attachments",
            target="Attachment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.attachments",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="visits",
            target="Visit",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.visits",
        ),
        SnakeRelationshipInfo(
            name="reactions",
            target="Reaction",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.reactions",
        ),
        SnakeRelationshipInfo(
            name="tags",
            target="Tag",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.tags",
        ),
    ),
    indexes=(
        SnakeIndexInfo(columns=("blog_id",)),
        SnakeIndexInfo(columns=("category_id",)),
        SnakeIndexInfo(columns=("author_id",)),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(comments),
    CreateTable(reactions),
    CreateTable(visits),
    AddForeignKey(
        comments,
        SnakeRelationshipInfo(
            name="author",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.users",
        ),
        users,
    ),
    AddForeignKey(
        comments,
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        posts,
    ),
    AddForeignKey(
        reactions,
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        posts,
    ),
    AddForeignKey(
        reactions,
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        users,
    ),
    AddForeignKey(
        visits,
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        posts,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
