"""Migration generated by SnakeORM. Editable by hand.

`Post.visit_count` and the trigger that keeps it. Counting `visits` is the honest query and the one
that does not scale — the volume table carries millions of rows — so the number is denormalised, and
kept by the ENGINE rather than by whoever happens to insert a visit.

The order is not cosmetic: the column has to exist before a trigger can write to it.
"""

from __future__ import annotations

from snakeorm import SnakeTriggerEvent, SnakeTriggerTiming
from snakeorm import SnakeIntSize
from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeIntParams,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
    SnakeTriggerInfo,
)
from snakeorm.migration import (
    AddColumn,
    CreateTrigger,
    Migration,
    SnakeOperation,
)

version = "0002_visit_counter"

_id = SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True)

posts = SnakeTableInfo(
    name="posts",
    columns=(_id,),
    primary_key=SnakePrimaryKeyInfo(columns=(_id,)),
)

visit_count = SnakeColumnInfo(
    name="visit_count",
    python_type=int,
    default=0,
    has_default=True,
    attr_name="visit_count",
    type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
)

operations: list[SnakeOperation] = [
    AddColumn(posts, visit_count),
    # The body is written ONCE, inline. On PostgreSQL a trigger calls a function instead, so the
    # dialect wraps this and emits the call; on MySQL and SQLite it goes as it is. Writing it three
    # times to say one thing is what that translation exists to avoid.
    CreateTrigger(
        SnakeTriggerInfo(
            name="tg_bump_visit_count",
            table="visits",
            timing=SnakeTriggerTiming.AFTER,
            events=(SnakeTriggerEvent.INSERT,),
            body="UPDATE posts SET visit_count = visit_count + 1 WHERE id = NEW.post_id;",
        )
    ),
]

migration = Migration(version=version, operations=tuple(operations))
