"""Column inheritance (and inheritance of a relationship) against a real Postgres.

Two models (ExArticle, ExNote of this own domain) inherit from the SAME abstract base
`InhOwnedBase`, which contributes id (auto), created_at (server_default) and the `owner` FK. The DDL
is generated from the compiled metadata (no hand-written SQL): that is how we check that the
INHERITED columns and relationship really exist in the table and make the round trip to the DB.

Its OWN schema with UNIQUE table names (`inh_e2e_*`) so as not to clash with the global registry.
"""

from __future__ import annotations

from snakeorm import SnakeUtc, snake_datetimetz

from datetime import datetime

import psycopg2
import pytest

from test.conftest import NO_SERVER_REASON

from snakeorm.decorators import snake_model, snake_table
from snakeorm.dialects.postgres import PostgresDialect
from snakeorm.drivers.psycopg import PsycopgDriver
from snakeorm.fields import (
    SnakeColumn,
    SnakeToOne,
    snake_auto,
    snake_int,
    snake_str,
    snake_to_one,
)
from snakeorm.linker.linker import snake_link
from snakeorm.metadata import SnakeRelationshipKind, SnakeServerDefault
from snakeorm.migration import emit_add_foreign_key, emit_create_table
from snakeorm.model import SnakeModel
from snakeorm.query import SnakeQuery
from snakeorm.registry import registry
from snakeorm.session import SnakeSession
from test.scenarios.db import dsn

pytestmark = pytest.mark.integration


@snake_model(table="inh_e2e_owners")
class InhOwner(SnakeModel):
    """Owner the FK inherited by the children points at."""

    id: SnakeColumn[int] = snake_auto()
    name: SnakeColumn[str] = snake_str()


class InhOwnedBase(SnakeModel):
    """Shared ABSTRACT base: id (auto), created_at (server_default) and the owner FK.

    It carries NO @snake_model: it is not a table. The children inherit these three columns and the
    relationship.
    """

    id: SnakeColumn[int] = snake_auto()
    created_at: SnakeColumn[SnakeUtc] = snake_datetimetz(
        server_default=SnakeServerDefault.NOW
    )
    owner_id: SnakeColumn[int] = snake_int()
    owner: SnakeToOne[InhOwner] = snake_to_one(owner_id)


@snake_model(table="inh_e2e_articles")
class InhArticle(InhOwnedBase):
    """Inherits id, created_at, owner_id and the owner relationship; adds title."""

    title: SnakeColumn[str] = snake_str()


@snake_model(table="inh_e2e_notes")
class InhNote(InhOwnedBase):
    """Another model inheriting from the SAME base; adds body."""

    body: SnakeColumn[str] = snake_str()


_MODELS = (InhOwner, InhArticle, InhNote)


@pytest.fixture(scope="module")
def session() -> SnakeSession:
    """Creates the schema from the compiled metadata and returns a session against a real Postgres."""
    try:
        connection = psycopg2.connect(dsn())
    except psycopg2.OperationalError:  # pragma: no cover - with no DB there is no test
        pytest.skip(NO_SERVER_REASON)
    snake_link()
    dialect = PostgresDialect()
    driver = PsycopgDriver(connection)
    tables = [snake_table(model) for model in _MODELS]
    references = ", ".join(
        f"{dialect.quote_ident(table.schema)}.{dialect.quote_ident(table.name)}"
        for table in tables
    )
    driver.execute(f"DROP TABLE IF EXISTS {references} CASCADE", ())
    for table in tables:
        driver.execute(emit_create_table(table, dialect), ())
    for table in tables:
        for relationship in table.relationships:
            if relationship.kind is not SnakeRelationshipKind.TO_ONE:
                continue
            target = registry.table_by_name(relationship.target)
            assert target is not None
            driver.execute(
                emit_add_foreign_key(table, relationship, target, dialect), ()
            )
    driver.commit()
    return SnakeSession(driver, dialect)


def test_inherited_columns_persist_and_roundtrip(session: SnakeSession) -> None:
    """The inherited columns (id auto, created_at server_default) are stored and read back."""
    owner = session.add(InhOwner(name="Ana"))
    article = session.add(InhArticle(title="Hola", owner_id=owner.id))
    assert isinstance(article.id, int)  # inherited id, generated by the DB (RETURNING)
    assert isinstance(
        article.created_at, datetime
    )  # inherited created_at, server_default NOW

    reloaded = session.first(SnakeQuery(InhArticle).filter(InhArticle.id == article.id))
    assert reloaded is not None
    assert reloaded.title == "Hola"
    assert isinstance(reloaded.created_at, datetime)


def test_two_models_share_the_same_base(session: SnakeSession) -> None:
    """Two different models inherit from the SAME base and each has its inherited columns."""
    owner = session.add(InhOwner(name="Bea"))
    note = session.add(InhNote(body="Recordatorio", owner_id=owner.id))
    assert isinstance(note.id, int)
    assert isinstance(note.created_at, datetime)

    reloaded = session.first(SnakeQuery(InhNote).filter(InhNote.id == note.id))
    assert reloaded is not None and reloaded.body == "Recordatorio"


def test_inherited_relation_loads_via_include(session: SnakeSession) -> None:
    """The INHERITED relationship (owner) links up and loads with include(): the child reaches its parent."""
    owner = session.add(InhOwner(name="Carla"))
    article = session.add(InhArticle(title="With an owner", owner_id=owner.id))

    loaded = session.all(
        SnakeQuery(InhArticle)
        .include(InhArticle.owner)
        .filter(InhArticle.id == article.id)
    )[0]
    assert loaded.owner.name == "Carla"
