"""Emission of parametrised INSERTs (single row, bulk, upsert): `INSERT INTO ... (cols) VALUES (...)`.

They delegate to the dialect the quoting, the placeholders, the conflict clause and `RETURNING`,
which returns ALL the columns so as to recover whatever the server puts there (autoincrement PK,
DEFAULT, triggers). Values go into `params`; never interpolated.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence

from snakeorm.dialects import SnakeDialect
from snakeorm.core.exceptions import SnakeEmitError
from snakeorm.dialects.capabilities import EmptyInsertStyle
from snakeorm.metadata import SnakeTableInfo
from snakeorm.sql.refs import qualified


def emit_insert(
    table: SnakeTableInfo,
    dialect: SnakeDialect,
    values: Mapping[str, object],
) -> tuple[str, tuple[object, ...]]:
    """Emits `INSERT INTO ... VALUES ...` with RETURNING where applicable.

    With no values the row is all defaults, and there each engine writes something different:
    `DEFAULT VALUES` is the standard and MySQL does NOT have it —it wants `() VALUES ()`—, so the
    shape is decided by `dialect.syntax`. A PK-only table is legitimate and must be insertable on all
    three.
    """
    if not values:
        table_ref = qualified(table.schema, table.name, dialect)
        empty_row = (
            "DEFAULT VALUES"
            if dialect.syntax.empty_insert_style is EmptyInsertStyle.DEFAULT_VALUES
            else "() VALUES ()"
        )
        return f"INSERT INTO {table_ref} {empty_row}{_returning(table, dialect)}", ()

    columns = list(values)
    params: list[object] = []
    row_sql = _emit_row(columns, values, dialect, params)
    sql = f"{_insert_head(table, dialect, columns)} VALUES {row_sql}"
    return f"{sql}{_returning(table, dialect)}", tuple(params)


def emit_insert_many(
    table: SnakeTableInfo,
    dialect: SnakeDialect,
    rows: Sequence[Mapping[str, object]],
) -> tuple[str, tuple[object, ...]]:
    """Emits a single `INSERT ... VALUES (...), (...), ...` for several rows.

    One single INSERT (not executemany) so that `RETURNING` recovers every row in one go. They must
    all have the same columns in the same order, or `SnakeEmitError`. The chunking lives in the
    session.
    """
    if not rows:
        raise SnakeEmitError("A bulk INSERT needs at least one row")
    columns = list(rows[0])
    if not columns:
        raise SnakeEmitError("An INSERT needs at least one column with a value")
    expected = set(columns)
    for row in rows:
        if set(row) != expected:
            raise SnakeEmitError(
                "Every row of a bulk INSERT must have the same columns; "
                f"{sorted(expected)} were expected."
            )

    params: list[object] = []
    tuples = ", ".join(_emit_row(columns, row, dialect, params) for row in rows)
    sql = f"{_insert_head(table, dialect, columns)} VALUES {tuples}"
    return f"{sql}{_returning(table, dialect)}", tuple(params)


def emit_upsert(
    table: SnakeTableInfo,
    dialect: SnakeDialect,
    values: Mapping[str, object],
    *,
    conflict_columns: Sequence[str],
    update_columns: Sequence[str] = (),
) -> tuple[str, tuple[object, ...]]:
    """Emits an INSERT idempotent under conflict: `INSERT ... <conflict clause> [RETURNING]`.

    The clause (`ON CONFLICT`) is supplied by the dialect. Without `update_columns` it does not touch
    the existing row. An empty `conflict_columns` is an error. Checking upsert support is the
    session's business.
    """
    if not conflict_columns:
        raise SnakeEmitError(
            "An upsert needs at least one conflict column (on_conflict)"
        )
    if not values:
        # Here it does NOT fall back to `DEFAULT VALUES`: SQLite forbids combining it with `ON
        # CONFLICT`, and an upsert with no values makes no sense (the conflict would be on the
        # autogenerated PK, which never collides).
        raise SnakeEmitError(
            "An upsert needs at least one value to insert: conflict resolution is meaningless "
            "for a row without columns (the conflict would be on the autogenerated PK, which "
            "never collides). Use `add` if you only want to insert."
        )

    conflict = dialect.on_conflict_clause(conflict_columns, update_columns)
    columns = list(values)
    params: list[object] = []
    row_sql = _emit_row(columns, values, dialect, params)
    sql = f"{_insert_head(table, dialect, columns)} VALUES {row_sql} {conflict}"
    return f"{sql}{_returning(table, dialect)}", tuple(params)


def _insert_head(
    table: SnakeTableInfo, dialect: SnakeDialect, columns: Sequence[str]
) -> str:
    """`INSERT INTO <schema.table> (<quoted cols>)`: header shared by the three emitters."""
    quoted_columns = ", ".join(dialect.quote_ident(column) for column in columns)
    table_ref = qualified(table.schema, table.name, dialect)
    return f"INSERT INTO {table_ref} ({quoted_columns})"


def _emit_row(
    columns: Sequence[str],
    values: Mapping[str, object],
    dialect: SnakeDialect,
    params: list[object],
) -> str:
    """`(ph, ph, ...)` for one row: every value enters `params` and numbers its placeholder.

    It walks `columns` (not `values`) to fix the order shared by every row; the numbering runs
    continuously across rows (which matters on positional dialects, `$1`, `$2`).
    """
    placeholders: list[str] = []
    for column in columns:
        params.append(values[column])
        placeholders.append(dialect.placeholder(len(params)))
    return f"({', '.join(placeholders)})"


def _returning(table: SnakeTableInfo, dialect: SnakeDialect) -> str:
    """` RETURNING <every column>` if the engine supports it, otherwise empty.

    ALL of them (not just the PK): it recovers whatever the server puts there (autoincrement,
    DEFAULT).
    """
    if not dialect.supports_returning:
        return ""
    columns = ", ".join(dialect.quote_ident(column.name) for column in table.columns)
    return f" RETURNING {columns}"
