"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import snakeorm.times

import shared.models.blog_models

from snakeorm.metadata import (
    SnakeDateTimeParams,
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeTableInfo,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_taxonomy_initial"

post_tags = SnakeTableInfo(
    name="post_tags",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="post_id",
            python_type=int,
            index=True,
            attr_name="post_id",
        ),
        SnakeColumnInfo(name="tag_id", python_type=int, index=True, attr_name="tag_id"),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="tag",
            target="Tag",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Tag", pairs=(("tag_id", "id"),)),
            target_table="public.tags",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("post_id",)), SnakeIndexInfo(columns=("tag_id",))),
)

tag_groups = SnakeTableInfo(
    name="tag_groups",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="name", python_type=str, unique=True, attr_name="name"),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="tags",
            target="Tag",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="TagGroup",
                pairs=(("group_id", "id"),),
            ),
            target_table="public.tags",
        ),
    ),
)

tags = SnakeTableInfo(
    name="tags",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="name", python_type=str, unique=True, attr_name="name"),
        SnakeColumnInfo(
            name="group_id",
            python_type=int,
            index=True,
            attr_name="group_id",
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="group",
            target="TagGroup",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="TagGroup",
                pairs=(("group_id", "id"),),
            ),
            target_table="public.tag_groups",
        ),
        SnakeRelationshipInfo(
            name="posts",
            target="Post",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="Tag", pairs=(("tag_id", "id"),)),
            target_table="public.posts",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("group_id",)),),
)

posts = SnakeTableInfo(
    name="posts",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="title", python_type=str, attr_name="title"),
        SnakeColumnInfo(name="body", python_type=str, attr_name="body"),
        SnakeColumnInfo(
            name="published",
            python_type=bool,
            default=False,
            has_default=True,
            attr_name="published",
        ),
        SnakeColumnInfo(
            name="blog_id",
            python_type=int,
            index=True,
            attr_name="blog_id",
        ),
        SnakeColumnInfo(
            name="category_id",
            python_type=int,
            nullable=True,
            index=True,
            attr_name="category_id",
        ),
        SnakeColumnInfo(
            name="author_id",
            python_type=int,
            index=True,
            attr_name="author_id",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            default_factory=shared.models.blog_models.utcnow,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="blog",
            target="Blog",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Blog", pairs=(("blog_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="category",
            target="Category",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Category",
                pairs=(("category_id", "id"),),
            ),
            target_table="public.categories",
        ),
        SnakeRelationshipInfo(
            name="author",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.users",
        ),
        SnakeRelationshipInfo(
            name="revisions",
            target="PostRevision",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.post_revisions",
        ),
        SnakeRelationshipInfo(
            name="attachments",
            target="Attachment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.attachments",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="visits",
            target="Visit",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.visits",
        ),
        SnakeRelationshipInfo(
            name="reactions",
            target="Reaction",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.reactions",
        ),
        SnakeRelationshipInfo(
            name="tags",
            target="Tag",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.tags",
        ),
    ),
    indexes=(
        SnakeIndexInfo(columns=("blog_id",)),
        SnakeIndexInfo(columns=("category_id",)),
        SnakeIndexInfo(columns=("author_id",)),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(post_tags),
    CreateTable(tag_groups),
    CreateTable(tags),
    AddForeignKey(
        post_tags,
        SnakeRelationshipInfo(
            name="post",
            target="Post",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Post", pairs=(("post_id", "id"),)),
            target_table="public.posts",
        ),
        posts,
    ),
    AddForeignKey(
        post_tags,
        SnakeRelationshipInfo(
            name="tag",
            target="Tag",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Tag", pairs=(("tag_id", "id"),)),
            target_table="public.tags",
        ),
        tags,
    ),
    AddForeignKey(
        tags,
        SnakeRelationshipInfo(
            name="group",
            target="TagGroup",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="TagGroup",
                pairs=(("group_id", "id"),),
            ),
            target_table="public.tag_groups",
        ),
        tag_groups,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
