"""Migration generated by SnakeORM. Editable by hand.

The `(post_id, tag_id)` pair of the bridge becomes UNIQUE. `tag_post` looks the link up and inserts
it if it is not there, which is a SELECT and then an INSERT: two transactions can both find nothing
and both insert. That window closes in the database or it does not close.
"""

from __future__ import annotations

from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
)
from snakeorm.migration import (
    CreateIndex,
    Migration,
    SnakeOperation,
)

version = "0002_taxonomy_unique_tagging"

post_tags = SnakeTableInfo(
    name="post_tags",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="post_id",
            python_type=int,
            index=True,
            attr_name="post_id",
        ),
        SnakeColumnInfo(name="tag_id", python_type=int, index=True, attr_name="tag_id"),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
)

operations: list[SnakeOperation] = [
    CreateIndex(
        post_tags,
        SnakeIndexInfo(columns=("post_id", "tag_id"), unique=True),
    ),
]

migration = Migration(version=version, operations=tuple(operations))
