"""Migration generated by SnakeORM. Editable by hand.

The index on `post_tags(post_id)` stopped earning its place the day `0002` added the UNIQUE on
`(post_id, tag_id)`. A B-tree serves any filter on a LEFTMOST PREFIX of its columns, so the composite
already answers `WHERE post_id = ?` — measured on SQLite, which plans it as a covering index search.

What is left is a second index on the same leading column: a write on every insert, for nothing.
`tag_id` keeps its own, and that is the asymmetry that makes this a decision rather than tidying —
`tag_id` is NOT a prefix of the composite, so the filter page would scan without it.
"""

from __future__ import annotations

from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
)
from snakeorm.migration import DropIndex, Migration, SnakeOperation

version = "0003_drop_redundant_post_index"

_id = SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True)

post_tags = SnakeTableInfo(
    name="post_tags",
    columns=(_id,),
    primary_key=SnakePrimaryKeyInfo(columns=(_id,)),
)

operations: list[SnakeOperation] = [
    DropIndex(post_tags, SnakeIndexInfo(columns=("post_id",))),
]

migration = Migration(version=version, operations=tuple(operations))
