"""Migration generated by SnakeORM. Editable by hand.

A taxonomy is a HIERARCHY — the word means nothing else — and until now `tags` was a flat list of
labels. `parent_id` points at another row of the same table and is NULL for a root, which is what
lets the catalogue answer the two questions a reader arrives with: where am I, and what is under
this. Both are one `WITH RECURSIVE`; without the column they are one query per level.

THREE OPERATIONS AND THE ORDER MATTERS. The column has to exist before an index or a constraint can
name it, and the self-referencing foreign key comes last because it points at the very table it
lives in: `tags` is already there, so there is nothing to wait for but the column itself.

The index is not decoration. Every level of the recursion joins `snake_src.parent_id` against the
accumulated `id`, so without it each step scans the table — the one query the feature exists to
avoid, paid once per level instead of once per row.

WHY THE KEY ARRIVES AS A `RebuildTable` AND NOT AN `AddForeignKey`. SQLite has no
`ALTER TABLE ... ADD CONSTRAINT` and never will — `Cap.ADD_CONSTRAINT` — so a foreign key on a table
that ALREADY EXISTS can only get there by remaking the table around it, and this file was where the
history stopped on that engine. `RebuildTable` says the same thing without naming an engine: `tags`
goes from this constraint shape to that one. Postgres and MariaDB still get the single minimal
`ALTER TABLE ... ADD CONSTRAINT`, byte for byte what `AddForeignKey` emitted; SQLite gets the table
built again with the key inside it. One operation, three spellings.

The column and its index stay OUTSIDE the rebuild, and not by preference: `RebuildTable` refuses a
pair of snapshots that disagree about anything but constraints, so `AddColumn` and `CreateIndex`
could not travel inside it. That refusal is the right one — a column change hidden inside a rebuild
is a column change with no operation naming it, and the tools that read a history read operations.

THE SNAPSHOTS ARE COMPLETE ON PURPOSE. On SQLite the rebuild recreates the table from `after`, so
anything absent from that snapshot is structure lost in silence: both carry every column, the
primary key, the group key, the through-relation and BOTH indexes. The indexes are identical on the
two sides because the rebuild drops them with the table and puts them back from `after` — which is
also why `CreateIndex` runs before it and not after. `tags` has no triggers, so `triggers=()` is the
truth and not an omission: a rebuild over a table the state knows triggers for refuses to apply.
"""

from __future__ import annotations

from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipInfo,
    SnakeRelationshipKind,
    SnakeTableInfo,
)
from snakeorm.migration import (
    AddColumn,
    CreateIndex,
    Migration,
    RebuildTable,
    SnakeOperation,
)

version = "0004_tag_hierarchy"

_id = SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True)
_name = SnakeColumnInfo(name="name", python_type=str, unique=True, attr_name="name")
_group_id = SnakeColumnInfo(
    name="group_id",
    python_type=int,
    index=True,
    attr_name="group_id",
)
parent_id = SnakeColumnInfo(
    name="parent_id",
    python_type=int,
    nullable=True,
    index=True,
    attr_name="parent_id",
)

_group = SnakeRelationshipInfo(
    name="group",
    target="TagGroup",
    kind=SnakeRelationshipKind.TO_ONE,
    foreign_key=SnakeForeignKeyInfo(target="TagGroup", pairs=(("group_id", "id"),)),
    target_table="public.tag_groups",
)
_posts = SnakeRelationshipInfo(
    name="posts",
    target="Post",
    kind=SnakeRelationshipKind.TO_MANY_THROUGH,
    foreign_key=SnakeForeignKeyInfo(target="Tag", pairs=(("tag_id", "id"),)),
    target_table="public.posts",
)
_parent = SnakeRelationshipInfo(
    name="parent",
    target="Tag",
    kind=SnakeRelationshipKind.TO_ONE,
    foreign_key=SnakeForeignKeyInfo(target="Tag", pairs=(("parent_id", "id"),)),
    target_table="public.tags",
)

_columns = (_id, _name, _group_id, parent_id)
_primary_key = SnakePrimaryKeyInfo(columns=(_id,))
_indexes = (
    SnakeIndexInfo(columns=("group_id",)),
    SnakeIndexInfo(columns=("parent_id",)),
)

# `tags` with the column and its index already in place, and the self-key not yet — which is exactly
# where the two operations above leave it.
tags_before = SnakeTableInfo(
    name="tags",
    columns=_columns,
    primary_key=_primary_key,
    relationships=(_group, _posts),
    indexes=_indexes,
)
tags_after = SnakeTableInfo(
    name="tags",
    columns=_columns,
    primary_key=_primary_key,
    relationships=(_group, _parent, _posts),
    indexes=_indexes,
)

# The table the two operations below name still has neither the column nor the index; a migration
# describes the schema AT ITS MOMENT, and this is `tags` as `0001` created it.
tags = SnakeTableInfo(
    name="tags",
    columns=(_id, _name, _group_id),
    primary_key=_primary_key,
    relationships=(_group, _posts),
    indexes=(SnakeIndexInfo(columns=("group_id",)),),
)

operations: list[SnakeOperation] = [
    AddColumn(tags, parent_id),
    CreateIndex(tags, SnakeIndexInfo(columns=("parent_id",))),
    RebuildTable(tags_before, tags_after, triggers=()),
]

migration = Migration(version=version, operations=tuple(operations))
