"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import datetime
import decimal
import shared.models.inventory_models
import shared.models.orders_models
import snakeorm.times
import uuid

from snakeorm.metadata import (
    SnakeCheckInfo,
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeDecimalParams,
    SnakeEnumStorage,
    SnakeFloatParams,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakeIntParams,
    SnakeIntSize,
    SnakeJsonParams,
    SnakeJsonStorage,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeStrParams,
    SnakeTableInfo,
    SnakeTimeParams,
)
from snakeorm.expressions import (
    SnakeComparison,
    SnakeExpr,
    SnakeInList,
    SnakeOp,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_orders_initial"

order_lines = SnakeTableInfo(
    name="order_lines",
    columns=(
        SnakeColumnInfo(
            name="order_id",
            python_type=int,
            attr_name="order_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="sku_id",
            python_type=int,
            attr_name="sku_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="quantity",
            python_type=int,
            attr_name="quantity",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="unit_price",
            python_type=decimal.Decimal,
            attr_name="unit_price",
            type_params=SnakeDecimalParams(precision=12, scale=2),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="order_id",
                python_type=int,
                attr_name="order_id",
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
            SnakeColumnInfo(
                name="sku_id",
                python_type=int,
                attr_name="sku_id",
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="order",
            target="Order",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Order",
                pairs=(("order_id", "id"),),
            ),
            target_table="public.orders",
        ),
        SnakeRelationshipInfo(
            name="sku",
            target="Sku",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.skus",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("quantity",)), SnakeOp.GT, 0),
            name="ck_order_lines_quantity_positive",
        ),
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("unit_price",)), SnakeOp.GE, 0),
            name="ck_order_lines_unit_price_not_negative",
        ),
    ),
    db_comment="One SKU wanted by one order",
)

orders = SnakeTableInfo(
    name="orders",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reference",
            python_type=str,
            unique=True,
            attr_name="reference",
            type_params=SnakeStrParams(max_length=24, fixed=False),
        ),
        SnakeColumnInfo(
            name="state",
            python_type=shared.models.orders_models.OrderState,
            default="draft",
            has_default=True,
            index=True,
            attr_name="state",
            enum_type=shared.models.orders_models.OrderState,
            enum_storage=SnakeEnumStorage.CHECK,
        ),
        SnakeColumnInfo(
            name="total",
            python_type=decimal.Decimal,
            attr_name="total",
            type_params=SnakeDecimalParams(precision=12, scale=2),
        ),
        SnakeColumnInfo(
            name="customer_id",
            python_type=int,
            index=True,
            attr_name="customer_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="warehouse_id",
            python_type=int,
            index=True,
            attr_name="warehouse_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="invoice_id",
            python_type=int,
            nullable=True,
            index=True,
            attr_name="invoice_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="placed_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="placed_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="customer",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("customer_id", "id"),),
            ),
            target_table="public.users",
        ),
        SnakeRelationshipInfo(
            name="warehouse",
            target="Warehouse",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouses",
        ),
        SnakeRelationshipInfo(
            name="invoice",
            target="Invoice",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.invoices",
        ),
        SnakeRelationshipInfo(
            name="lines",
            target="OrderLine",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Order",
                pairs=(("order_id", "id"),),
            ),
            target_table="public.order_lines",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeInList(
                SnakeExpr(path=("state",)),
                ("draft", "reserved", "invoiced", "settled", "cancelled"),
            ),
        ),
    ),
    db_comment="Customer orders: the joint between stock and billing",
    indexes=(
        SnakeIndexInfo(columns=("state",)),
        SnakeIndexInfo(columns=("customer_id",)),
        SnakeIndexInfo(columns=("warehouse_id",)),
        SnakeIndexInfo(columns=("invoice_id",)),
        SnakeIndexInfo(
            columns=("warehouse_id", "state"),
            name="ix_orders_warehouse_state",
        ),
    ),
)

skus = SnakeTableInfo(
    name="skus",
    columns=(
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="public_id",
            python_type=uuid.UUID,
            attr_name="public_id",
            default_factory=uuid.uuid4,
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            attr_name="name",
            type_params=SnakeStrParams(max_length=120, fixed=False),
        ),
        SnakeColumnInfo(
            name="kind",
            python_type=shared.models.inventory_models.SkuKind,
            default="physical",
            has_default=True,
            attr_name="kind",
            enum_type=shared.models.inventory_models.SkuKind,
            enum_storage=SnakeEnumStorage.CHECK,
        ),
        SnakeColumnInfo(
            name="price",
            python_type=decimal.Decimal,
            attr_name="price",
            type_params=SnakeDecimalParams(precision=12, scale=2),
        ),
        SnakeColumnInfo(
            name="weight_kg",
            python_type=float,
            attr_name="weight_kg",
            type_params=SnakeFloatParams(size=4),
        ),
        SnakeColumnInfo(
            name="lead_time",
            python_type=datetime.timedelta,
            attr_name="lead_time",
        ),
        SnakeColumnInfo(
            name="thumbnail",
            python_type=bytes,
            nullable=True,
            default=None,
            has_default=True,
            attr_name="thumbnail",
        ),
        SnakeColumnInfo(
            name="attrs",
            python_type=dict,
            attr_name="attrs",
            type_params=SnakeJsonParams(storage=SnakeJsonStorage.JSONB),
        ),
        SnakeColumnInfo(
            name="related_ids",
            python_type=list[int],
            attr_name="related_ids",
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.warehouse_stock",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeInList(
                SnakeExpr(path=("kind",)),
                ("physical", "digital", "service"),
            ),
        ),
    ),
    db_comment="Catalogue of stockable items",
)

users = SnakeTableInfo(
    name="users",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="username",
            python_type=str,
            unique=True,
            attr_name="username",
            type_params=SnakeStrParams(max_length=None, fixed=False),
        ),
        SnakeColumnInfo(
            name="email",
            python_type=str,
            unique=True,
            attr_name="email",
            type_params=SnakeStrParams(max_length=None, fixed=False),
        ),
        SnakeColumnInfo(
            name="password_hash",
            python_type=str,
            attr_name="password_hash",
            type_params=SnakeStrParams(max_length=None, fixed=False),
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="roles",
            target="Role",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.roles",
        ),
        SnakeRelationshipInfo(
            name="api_tokens",
            target="ApiToken",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.api_tokens",
        ),
        SnakeRelationshipInfo(
            name="sessions",
            target="LoginSession",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.login_sessions",
        ),
        SnakeRelationshipInfo(
            name="blogs",
            target="Blog",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("owner_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="posts",
            target="Post",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="subscriptions",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.subscriptions",
        ),
        SnakeRelationshipInfo(
            name="orders",
            target="Order",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("customer_id", "id"),),
            ),
            target_table="public.orders",
        ),
    ),
)

invoices = SnakeTableInfo(
    name="invoices",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="amount_cents",
            python_type=int,
            attr_name="amount_cents",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="paid",
            python_type=bool,
            default=False,
            has_default=True,
            attr_name="paid",
        ),
        SnakeColumnInfo(
            name="subscription_id",
            python_type=int,
            index=True,
            attr_name="subscription_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="issued_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="issued_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="subscription",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Subscription",
                pairs=(("subscription_id", "id"),),
            ),
            target_table="public.subscriptions",
        ),
        SnakeRelationshipInfo(
            name="payments",
            target="Payment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.payments",
        ),
        SnakeRelationshipInfo(
            name="orders",
            target="Order",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.orders",
        ),
    ),
    indexes=(SnakeIndexInfo(columns=("subscription_id",)),),
)

warehouses = SnakeTableInfo(
    name="warehouses",
    columns=(
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="code",
            python_type=str,
            unique=True,
            attr_name="code",
            type_params=SnakeStrParams(max_length=3, fixed=True),
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            attr_name="name",
            type_params=SnakeStrParams(max_length=80, fixed=False),
        ),
        SnakeColumnInfo(
            name="active",
            python_type=bool,
            default=True,
            has_default=True,
            attr_name="active",
        ),
        SnakeColumnInfo(
            name="opened_on",
            python_type=datetime.date,
            attr_name="opened_on",
        ),
        SnakeColumnInfo(
            name="shift_start",
            python_type=datetime.time,
            attr_name="shift_start",
            type_params=SnakeTimeParams(with_timezone=False),
        ),
        SnakeColumnInfo(
            name="cutoff",
            python_type=datetime.time,
            attr_name="cutoff",
            type_params=SnakeTimeParams(with_timezone=True),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="stock",
            target="Stock",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouse_stock",
        ),
        SnakeRelationshipInfo(
            name="orders",
            target="Order",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.orders",
        ),
    ),
    db_comment="Physical warehouses that hold stock",
    indexes=(
        SnakeIndexInfo(
            columns=("code",),
            name="ix_warehouses_active_code",
            where=SnakeComparison(SnakeExpr(path=("active",)), SnakeOp.EQ, True),
        ),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(order_lines),
    CreateTable(orders),
    AddForeignKey(
        order_lines,
        SnakeRelationshipInfo(
            name="order",
            target="Order",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Order",
                pairs=(("order_id", "id"),),
            ),
            target_table="public.orders",
        ),
        orders,
    ),
    AddForeignKey(
        order_lines,
        SnakeRelationshipInfo(
            name="sku",
            target="Sku",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Sku", pairs=(("sku_id", "id"),)),
            target_table="public.skus",
        ),
        skus,
    ),
    AddForeignKey(
        orders,
        SnakeRelationshipInfo(
            name="customer",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("customer_id", "id"),),
            ),
            target_table="public.users",
        ),
        users,
    ),
    AddForeignKey(
        orders,
        SnakeRelationshipInfo(
            name="invoice",
            target="Invoice",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Invoice",
                pairs=(("invoice_id", "id"),),
            ),
            target_table="public.invoices",
        ),
        invoices,
    ),
    AddForeignKey(
        orders,
        SnakeRelationshipInfo(
            name="warehouse",
            target="Warehouse",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Warehouse",
                pairs=(("warehouse_id", "id"),),
            ),
            target_table="public.warehouses",
        ),
        warehouses,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
