"""Migration generated by SnakeORM. Editable by hand.

The index on `orders(warehouse_id)` is redundant with `ix_orders_warehouse_state`, which indexes
`(warehouse_id, state)`. A B-tree answers a filter on a leftmost prefix of its columns, so the
composite already serves `WHERE warehouse_id = ?`; the single-column one costs a write per insert and
answers nothing the other does not.

It is the same argument as `taxonomy/0003`, on a different table, and both were found by listing the
declared indexes of every model side by side rather than by reading one at a time.
"""

from __future__ import annotations

from snakeorm.metadata import (
    SnakeColumnInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeTableInfo,
)
from snakeorm.migration import DropIndex, Migration, SnakeOperation

version = "0002_drop_redundant_warehouse_index"

_id = SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True)

orders = SnakeTableInfo(
    name="orders",
    columns=(_id,),
    primary_key=SnakePrimaryKeyInfo(columns=(_id,)),
)

operations: list[SnakeOperation] = [
    DropIndex(orders, SnakeIndexInfo(columns=("warehouse_id",))),
]

migration = Migration(version=version, operations=tuple(operations))
