"""auth domain use cases (API tokens and login sessions), written once.

The token secret is GENERATED by the use case (the client does not supply it): `secrets.token_urlsafe`,
expiring in 30 days. The value is only returned when issued; from then on the DTOs redact it.
"""

from __future__ import annotations

import secrets
from datetime import timedelta

from snakeorm import SnakeUtc, SnakeSession

from shared.models import ApiToken, LoginSession
from shared.selectors import auth_selectors as selectors
from shared.services import auth_services as services
from shared.usecases.result import Failure

# Default lifetime of a freshly issued token.
_TOKEN_TTL = timedelta(days=30)


def tokens_of_user(session: SnakeSession, user_id: int) -> list[ApiToken]:
    """Every token of a user (active and revoked)."""
    return selectors.tokens_of_user(session, user_id)


def active_tokens(session: SnakeSession, user_id: int) -> list[ApiToken]:
    """A user's tokens that have NOT been revoked, newest first.

    THIS DOCSTRING USED TO SAY "neither revoked nor expired" AND THE QUERY HAS NEVER ASKED ABOUT
    EXPIRY. `auth_selectors.active_of` filters on `revoked` alone, so a token whose `expires_at` has
    gone by is answered here and served by `/api/auth/users/{id}/tokens/active`. The wording is
    corrected rather than the filter, because widening the filter changes what the endpoint answers
    on seeded data — the factory gives every token a random `expires_at`, most of them in the past —
    and that is a decision about the domain rather than about a sentence.

    It is written down instead of quietly fixed for the reason this repository keeps repeating: a
    name that promises more than it does is worse than no name at all, and the promise was in the
    only place a reader would look for it.
    """
    return selectors.active_tokens(session, user_id)


def sessions_of_user(session: SnakeSession, user_id: int) -> list[LoginSession]:
    """A user's login sessions."""
    return selectors.sessions_of_user(session, user_id)


def issue_token(
    session: SnakeSession, user_id: int, label: str | None = None
) -> ApiToken:
    """Issues a new token (generated secret, expiring in 30 days) and commits it."""
    now = SnakeUtc.now()
    token = services.issue_token(
        session, user_id, secrets.token_urlsafe(32), now + _TOKEN_TTL, label
    )
    session.commit()
    return token


def revoke_token(session: SnakeSession, token_id: int) -> None | Failure:
    """Revokes a token; `not_found` if it does not exist."""
    if not services.revoke_token(session, token_id):
        return Failure("not_found")
    session.commit()
    return None
