"""Migration generated by SnakeORM. Editable by hand."""

from __future__ import annotations

import snakeorm.times


from snakeorm.metadata import (
    SnakeDateTimeParams,
    SnakeColumnInfo,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakePrimaryKeyInfo,
    SnakeRelationshipKind,
    SnakeRelationshipInfo,
    SnakeServerDefault,
    SnakeTableInfo,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_accounts_initial"

roles = SnakeTableInfo(
    name="roles",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(name="name", python_type=str, unique=True, attr_name="name"),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="users",
            target="User",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="Role", pairs=(("role_id", "id"),)),
            target_table="public.users",
        ),
    ),
)

user_roles = SnakeTableInfo(
    name="user_roles",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="user_id",
            python_type=int,
            index=True,
            attr_name="user_id",
        ),
        SnakeColumnInfo(
            name="role_id",
            python_type=int,
            index=True,
            attr_name="role_id",
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        SnakeRelationshipInfo(
            name="role",
            target="Role",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Role", pairs=(("role_id", "id"),)),
            target_table="public.roles",
        ),
    ),
    indexes=(
        SnakeIndexInfo(columns=("user_id",)),
        SnakeIndexInfo(columns=("role_id",)),
    ),
)

users = SnakeTableInfo(
    name="users",
    columns=(
        SnakeColumnInfo(name="id", python_type=int, attr_name="id", autoincrement=True),
        SnakeColumnInfo(
            name="username",
            python_type=str,
            unique=True,
            attr_name="username",
        ),
        SnakeColumnInfo(name="email", python_type=str, unique=True, attr_name="email"),
        SnakeColumnInfo(
            name="password_hash",
            python_type=str,
            attr_name="password_hash",
        ),
        SnakeColumnInfo(
            name="created_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="created_at",
            server_default=SnakeServerDefault.NOW,
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="roles",
            target="Role",
            kind=SnakeRelationshipKind.TO_MANY_THROUGH,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.roles",
        ),
        SnakeRelationshipInfo(
            name="api_tokens",
            target="ApiToken",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.api_tokens",
        ),
        SnakeRelationshipInfo(
            name="sessions",
            target="LoginSession",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.login_sessions",
        ),
        SnakeRelationshipInfo(
            name="blogs",
            target="Blog",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("owner_id", "id"),)),
            target_table="public.blogs",
        ),
        SnakeRelationshipInfo(
            name="posts",
            target="Post",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.posts",
        ),
        SnakeRelationshipInfo(
            name="comments",
            target="Comment",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="User",
                pairs=(("author_id", "id"),),
            ),
            target_table="public.comments",
        ),
        SnakeRelationshipInfo(
            name="subscriptions",
            target="Subscription",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.subscriptions",
        ),
    ),
)

operations: list[SnakeOperation] = [
    CreateTable(roles),
    CreateTable(user_roles),
    CreateTable(users),
    AddForeignKey(
        user_roles,
        SnakeRelationshipInfo(
            name="role",
            target="Role",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="Role", pairs=(("role_id", "id"),)),
            target_table="public.roles",
        ),
        roles,
    ),
    AddForeignKey(
        user_roles,
        SnakeRelationshipInfo(
            name="user",
            target="User",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(target="User", pairs=(("user_id", "id"),)),
            target_table="public.users",
        ),
        users,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
