"""Immutable metadata of the foreign key (simple or composite)."""

from __future__ import annotations

from dataclasses import dataclass

from snakeorm.metadata.fk_action import SnakeFkAction


@dataclass(frozen=True, slots=True)
class SnakeForeignKeyInfo:
    """Foreign key: target model + (source_column, target_column) pairs.

    ONE single structure for a simple FK (1 pair) and a composite one (N pairs). The join is
    generated by AND-ing every pair together. `target` is the model's NAME (resolved in the Linker).
    """

    target: str
    pairs: tuple[tuple[str, str], ...]
    on_delete: SnakeFkAction = SnakeFkAction.NO_ACTION
    on_update: SnakeFkAction = SnakeFkAction.NO_ACTION

    @property
    def is_composite(self) -> bool:
        """Tells whether the key spans more than one column."""
        return len(self.pairs) > 1
