"""Default value set by the SERVER (not by the Python client)."""

from __future__ import annotations

from enum import Enum


class SnakeServerDefault(Enum):
    """Default value generated by the DATABASE when the row is inserted.

    Unlike `default` (a literal in the INSERT) and `default_factory` (a client-side callable), it
    OMITS the column from the INSERT so the server fills it in, and the RETURNING brings it back.
    Engine-agnostic values (not SQL): the dialect translates (`dialect.server_default_sql`).
    """

    NOW = "now"  # the server's current timestamp
    UUID_V4 = "uuid_v4"  # random uuid (version 4) generated by the DB
    TRUE = "true"  # boolean true
    FALSE = "false"  # boolean false
    ZERO = "zero"  # numeric zero
