"""Migration generated by SnakeORM, with ONE operation removed by hand.

The generator compared this domain's tables against the EMPTY history of this directory, and a
trigger is registered on the registry rather than on a table — so `tg_bump_visit_count`, which
belongs to `engagement` and is already created by that domain's own migration, came out here as
missing. Applying it twice is an error on every engine.

It is struck off rather than left with a comment beside it, and `test_migration_drift.py` is what
makes that safe: the trigger is still declared by the models and still created by `engagement`, so if
this removal had taken it out of the schema the drift check would say so by name.
"""

from __future__ import annotations

import snakeorm.times

from snakeorm.metadata import (
    SnakeCheckInfo,
    SnakeColumnInfo,
    SnakeDateTimeParams,
    SnakeFloatParams,
    SnakeForeignKeyInfo,
    SnakeIndexInfo,
    SnakeIntParams,
    SnakeIntSize,
    SnakePrimaryKeyInfo,
    SnakeRelationshipInfo,
    SnakeRelationshipKind,
    SnakeStrParams,
    SnakeTableInfo,
)
from snakeorm.expressions import (
    SnakeComparison,
    SnakeExpr,
    SnakeOp,
)
from snakeorm.migration import (
    AddForeignKey,
    CreateTable,
    Migration,
    SnakeOperation,
)

version = "0001_logistics_initial"

deliveries = SnakeTableInfo(
    name="deliveries",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="reference",
            python_type=str,
            unique=True,
            attr_name="reference",
            type_params=SnakeStrParams(max_length=20, fixed=False),
        ),
        SnakeColumnInfo(
            name="depot_id",
            python_type=int,
            index=True,
            attr_name="depot_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="packaging_id",
            python_type=int,
            index=True,
            attr_name="packaging_id",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="units",
            python_type=int,
            attr_name="units",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="latitude",
            python_type=float,
            attr_name="latitude",
            type_params=SnakeFloatParams(size=8),
        ),
        SnakeColumnInfo(
            name="longitude",
            python_type=float,
            attr_name="longitude",
            type_params=SnakeFloatParams(size=8),
        ),
        SnakeColumnInfo(
            name="slot_hour",
            python_type=int,
            attr_name="slot_hour",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="promised_at",
            python_type=snakeorm.times.SnakeUtc,
            attr_name="promised_at",
            type_params=SnakeDateTimeParams(tz=True, precision=None),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="depot",
            target="Depot",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Depot",
                pairs=(("depot_id", "id"),),
            ),
            target_table="public.depots",
        ),
        SnakeRelationshipInfo(
            name="packaging",
            target="PackagingUnit",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="PackagingUnit",
                pairs=(("packaging_id", "id"),),
            ),
            target_table="public.packaging_units",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("units",)), SnakeOp.GT, 0),
            name="ck_deliveries_units_positive",
        ),
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("slot_hour",)), SnakeOp.GE, 0),
            name="ck_deliveries_slot_hour_low",
        ),
        SnakeCheckInfo(
            condition=SnakeComparison(SnakeExpr(path=("slot_hour",)), SnakeOp.LE, 23),
            name="ck_deliveries_slot_hour_high",
        ),
    ),
    db_comment="Deliveries booked out of a depot",
    indexes=(
        SnakeIndexInfo(columns=("depot_id", "slot_hour")),
        SnakeIndexInfo(columns=("depot_id",)),
        SnakeIndexInfo(columns=("packaging_id",)),
    ),
)

depots = SnakeTableInfo(
    name="depots",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="code",
            python_type=str,
            unique=True,
            attr_name="code",
            type_params=SnakeStrParams(max_length=3, fixed=True),
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            attr_name="name",
            type_params=SnakeStrParams(max_length=80, fixed=False),
        ),
        SnakeColumnInfo(
            name="latitude",
            python_type=float,
            attr_name="latitude",
            type_params=SnakeFloatParams(size=8),
        ),
        SnakeColumnInfo(
            name="longitude",
            python_type=float,
            attr_name="longitude",
            type_params=SnakeFloatParams(size=8),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="deliveries",
            target="Delivery",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="Depot",
                pairs=(("depot_id", "id"),),
            ),
            target_table="public.deliveries",
        ),
    ),
    db_comment="Dispatch depots that vans leave from",
)

packaging_units = SnakeTableInfo(
    name="packaging_units",
    columns=(
        SnakeColumnInfo(
            name="id",
            python_type=int,
            attr_name="id",
            autoincrement=True,
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
        SnakeColumnInfo(
            name="name",
            python_type=str,
            unique=True,
            attr_name="name",
            type_params=SnakeStrParams(max_length=40, fixed=False),
        ),
        SnakeColumnInfo(
            name="units_per_box",
            python_type=int,
            attr_name="units_per_box",
            type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
        ),
    ),
    primary_key=SnakePrimaryKeyInfo(
        columns=(
            SnakeColumnInfo(
                name="id",
                python_type=int,
                attr_name="id",
                autoincrement=True,
                type_params=SnakeIntParams(size=SnakeIntSize.BIGINT),
            ),
        ),
    ),
    relationships=(
        SnakeRelationshipInfo(
            name="deliveries",
            target="Delivery",
            kind=SnakeRelationshipKind.TO_MANY,
            foreign_key=SnakeForeignKeyInfo(
                target="PackagingUnit",
                pairs=(("packaging_id", "id"),),
            ),
            target_table="public.deliveries",
        ),
    ),
    checks=(
        SnakeCheckInfo(
            condition=SnakeComparison(
                SnakeExpr(path=("units_per_box",)),
                SnakeOp.GT,
                0,
            ),
            name="ck_packaging_units_per_box",
        ),
    ),
    db_comment="Packaging kinds and how many units fit in one box",
)

operations: list[SnakeOperation] = [
    CreateTable(deliveries),
    CreateTable(depots),
    CreateTable(packaging_units),
    AddForeignKey(
        deliveries,
        SnakeRelationshipInfo(
            name="depot",
            target="Depot",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="Depot",
                pairs=(("depot_id", "id"),),
            ),
            target_table="public.depots",
        ),
        depots,
    ),
    AddForeignKey(
        deliveries,
        SnakeRelationshipInfo(
            name="packaging",
            target="PackagingUnit",
            kind=SnakeRelationshipKind.TO_ONE,
            foreign_key=SnakeForeignKeyInfo(
                target="PackagingUnit",
                pairs=(("packaging_id", "id"),),
            ),
            target_table="public.packaging_units",
        ),
        packaging_units,
    ),
]

migration = Migration(version=version, operations=tuple(operations))
