"""The production stack ASSEMBLED — timeout over logging over the pool over the real driver.

Every decorator has its own test and, until now, nobody had put them together with a pool
underneath. Measured on `docs/contributors/coverage-history/`: 52 functions in `drivers/` had never
been entered by any test, and they cluster in exactly the methods a decorator is most likely to
swallow — `release_savepoint`, `rollback_to_savepoint`, `fetch_iter` and `last_insert_id`, missing
from one wrapper while present on the one below.

A wrapper that drops a method does not fail loudly: it fails by the transaction not being what the
caller thinks it is. That is what this file is for.

`TimeoutDriver` deliberately cannot wrap SQLite — `statement_timeout_sql()` answers `None` there and
accepting the wrap would hand back a connection that looks capped and is not — so the SQLite half
stacks logging over the pool and says so, rather than pretending the two engines take the same tower.

`last_insert_id` needs a third stack. The session asks for it only on an engine without `RETURNING`,
so Postgres and SQLite can never reach it however they are wrapped: MySQL is where that path lives.
"""

from __future__ import annotations

import pathlib
from collections.abc import Iterator

import pytest

from test.conftest import NO_MYSQL_REASON, NO_SERVER_REASON

from snakeorm import (
    LoggingDriver,
    MySQLDialect,
    PostgresDialect,
    PyMySQLDriver,
    SnakeColumn,
    SnakeModel,
    SnakeQuery,
    SnakeSession,
    SQLiteDialect,
    SQLiteDriver,
    snake_auto,
    snake_int,
    snake_model,
    snake_str,
    snake_table,
)
from snakeorm.drivers.base import SnakeDriver
from snakeorm.drivers.pool import SnakePool, psycopg_pool
from snakeorm.drivers.timeout import TimeoutDriver
from snakeorm.migration import emit_create_table
from test.scenarios.db import dsn
from test.scenarios.engines import mysql_kwargs

pytestmark = pytest.mark.integration

_TABLE = "stack_widgets"


@snake_model(table=_TABLE)
class Widget(SnakeModel):
    """An explicit PK: these tests care about the transaction, not about who invents the id."""

    id: SnakeColumn[int] = snake_int(primary_key=True)
    name: SnakeColumn[str] = snake_str(max_length=50)


@snake_model(table="stack_autoids")
class Autoid(SnakeModel):
    """An AUTOGENERATED PK, which is the only way to reach `last_insert_id`.

    The session asks for it only on engines WITHOUT `RETURNING`, so this model exists for the MySQL
    stack: on Postgres and SQLite the PK comes back through RETURNING and the property is never
    read. That is why it was cold on every wrapper.
    """

    id: SnakeColumn[int] = snake_auto()
    name: SnakeColumn[str] = snake_str(max_length=50)


@pytest.fixture
def postgres_stack() -> Iterator[SnakeSession]:
    """timeout -> logging -> pool -> psycopg. The tower a production deployment actually builds.

    The pooled driver is INNERMOST, and that is not a detail: `pool.acquire()` hands back a
    `_PooledDriver` already wrapping the connection, so the decorators dress THAT. The consequence
    is the one that matters — `close()` walks down the chain and reaches a `close()` that gives the
    connection BACK instead of shutting it.
    """
    import psycopg2

    try:
        pool = psycopg_pool(dsn(), minimum=1, maximum=2)
    except psycopg2.OperationalError as error:  # pragma: no cover - environment
        pytest.skip(f"{NO_SERVER_REASON}: {error}")

    lines: list[str] = []
    borrowed = pool.acquire()
    driver: SnakeDriver = TimeoutDriver(
        LoggingDriver(borrowed, write=lines.append),
        PostgresDialect(),
        statement_timeout_ms=5000,
    )
    driver.execute(f"DROP TABLE IF EXISTS {_TABLE} CASCADE", ())
    driver.execute(emit_create_table(snake_table(Widget), PostgresDialect()), ())
    driver.commit()
    try:
        yield SnakeSession(driver, PostgresDialect())
    finally:
        driver.execute(f"DROP TABLE IF EXISTS {_TABLE} CASCADE", ())
        driver.commit()
        driver.close()
        pool.close()


@pytest.fixture
def sqlite_stack(tmp_path: pathlib.Path) -> Iterator[SnakeSession]:
    """pool -> logging -> sqlite3, and the missing layer is DECLARED rather than skipped over.

    There is no `TimeoutDriver` here because SQLite has no server-side statement timeout, and no
    shipped pool factory either: `SnakePool` takes the three operations, so they are written out.
    That is exactly what a user of another engine has to do, so writing it here proves the seam
    holds outside Postgres.
    """
    path = str(tmp_path / "stack.db")
    open_drivers: list[SQLiteDriver] = []

    def borrow() -> SnakeDriver:
        driver = SQLiteDriver.connect(path)
        open_drivers.append(driver)
        return driver

    def give_back(driver: SnakeDriver) -> None:
        """The pool keeps it: a file-backed SQLite survives being handed back."""

    def close_all() -> None:
        for driver in open_drivers:
            driver.close()

    pool = SnakePool(borrow, give_back, close_all)
    lines: list[str] = []
    driver: SnakeDriver = LoggingDriver(pool.acquire(), write=lines.append)
    driver.execute(emit_create_table(snake_table(Widget), SQLiteDialect()), ())
    driver.commit()
    try:
        yield SnakeSession(driver, SQLiteDialect())
    finally:
        driver.close()
        pool.close()


@pytest.fixture
def mysql_stack() -> Iterator[SnakeSession]:
    """timeout -> logging -> pool -> pymysql, and this is the ONLY tower that reaches `last_insert_id`.

    MySQL has no `RETURNING`, so it is the engine where the session asks the driver which id it just
    wrote — and therefore the only place a wrapper swallowing that property does damage. On the
    other two the PK comes back inside the INSERT and the whole path is unreachable.
    """
    import pymysql

    kwargs = mysql_kwargs()
    open_drivers: list[PyMySQLDriver] = []

    def borrow() -> SnakeDriver:
        driver = PyMySQLDriver.connect(**kwargs)  # type: ignore[arg-type]
        open_drivers.append(driver)
        return driver

    def give_back(driver: SnakeDriver) -> None:
        """Kept open: `close_all` shuts them at the end."""

    def close_all() -> None:
        for driver in open_drivers:
            driver.close()

    try:
        pool = SnakePool(borrow, give_back, close_all)
        borrowed = pool.acquire()
    except pymysql.err.OperationalError as error:  # pragma: no cover - environment
        pytest.skip(f"{NO_MYSQL_REASON}: {error}")

    lines: list[str] = []
    driver: SnakeDriver = TimeoutDriver(
        LoggingDriver(borrowed, write=lines.append),
        MySQLDialect(),
        statement_timeout_ms=5000,
    )
    for statement in (
        "DROP TABLE IF EXISTS stack_autoids",
        f"DROP TABLE IF EXISTS {_TABLE}",
        emit_create_table(snake_table(Autoid), MySQLDialect()),
        emit_create_table(snake_table(Widget), MySQLDialect()),
    ):
        driver.execute(statement, ())
    driver.commit()
    try:
        yield SnakeSession(driver, MySQLDialect())
    finally:
        driver.execute("DROP TABLE IF EXISTS stack_autoids", ())
        driver.execute(f"DROP TABLE IF EXISTS {_TABLE}", ())
        driver.commit()
        driver.close()
        pool.close()


def test_the_generated_id_climbs_back_up_the_whole_tower(
    mysql_stack: SnakeSession,
) -> None:
    """`last_insert_id` was cold on EVERY wrapper, and a swallowed one leaves the PK at `None`.

    It is asserted as a value and not as "not None": a wrapper forwarding to the wrong connection
    would answer some id, just not this row's, so the id is read back FROM THE TABLE.
    """
    written = mysql_stack.add(Autoid(name="first"))
    mysql_stack.commit()

    assert written.id, "the generated PK never came back up through the decorators"
    found = mysql_stack.first(SnakeQuery(Autoid).filter(Autoid.id == written.id))
    assert found is not None and found.name == "first", (
        f"the id that came back ({written.id}) does not name the row that was written"
    )


def _driver_of(session: SnakeSession) -> SnakeDriver:
    """The driver under a session. Private access, and deliberately in ONE place: the subject of
    this file is the driver stack, and there is no public way down to it from a session."""
    return session._driver  # noqa: SLF001


_STACKS = ["postgres_stack", "mysql_stack", "sqlite_stack"]
"""The three towers. They are NOT the same tower three times, and that is the point.

    postgres   timeout -> logging -> pool -> psycopg
    mysql      timeout -> logging -> pool -> pymysql
    sqlite     logging -> pool -> sqlite3        (no server-side statement timeout to cap)
"""


@pytest.mark.parametrize("stack", _STACKS)
def test_a_savepoint_released_through_the_whole_tower(
    stack: str, request: pytest.FixtureRequest
) -> None:
    """SAVEPOINT and RELEASE travel down every wrapper, and the write survives.

    `release_savepoint` was cold on `LoggingDriver`, `TimeoutDriver` and `_PooledDriver` at once —
    three layers where the call could be dropped, and dropping it leaves a savepoint open rather
    than failing.
    """
    session: SnakeSession = request.getfixturevalue(stack)

    session.add(Widget(id=1, name="before"))
    with session.savepoint():
        session.add(Widget(id=2, name="inside"))
    session.commit()

    assert session.count(SnakeQuery(Widget)) == 2, (
        "a released savepoint must keep what was written inside it"
    )


@pytest.mark.parametrize("stack", _STACKS)
def test_a_savepoint_rolled_back_through_the_whole_tower(
    stack: str, request: pytest.FixtureRequest
) -> None:
    """ROLLBACK TO SAVEPOINT discards only the inside, and the transaction stays alive.

    Both halves are read: checking only that the inner write vanished would pass on a stack that
    rolled the whole transaction back, which is the failure the savepoint exists to prevent.
    """
    session: SnakeSession = request.getfixturevalue(stack)

    class Boom(RuntimeError):
        pass

    session.add(Widget(id=1, name="before"))
    with pytest.raises(Boom):
        with session.savepoint():
            session.add(Widget(id=2, name="inside"))
            raise Boom
    session.commit()

    names = [row.name for row in session.all(SnakeQuery(Widget))]
    assert names == ["before"], f"the savepoint took more than its own block: {names}"


@pytest.mark.parametrize("stack", _STACKS)
def test_streaming_walks_the_rows_through_every_wrapper(
    stack: str, request: pytest.FixtureRequest
) -> None:
    """`iterate()` reaches `fetch_iter`, which was cold on all three wrappers at once.

    A chunk smaller than the row count on purpose: with one chunk a broken `fetch_iter` that fell
    back to `fetch_all` would pass.
    """
    session: SnakeSession = request.getfixturevalue(stack)

    for number in range(1, 6):
        session.add(Widget(id=number, name=f"w{number}"))
    session.commit()

    walked = [row.name for row in session.iterate(SnakeQuery(Widget), chunk=2)]

    assert walked == ["w1", "w2", "w3", "w4", "w5"]


@pytest.mark.parametrize("stack", _STACKS)
def test_a_rollback_travels_down_the_tower(
    stack: str, request: pytest.FixtureRequest
) -> None:
    """`rollback` was cold on `TimeoutDriver` and `_PooledDriver`: a swallowed one keeps the write."""
    session: SnakeSession = request.getfixturevalue(stack)

    session.add(Widget(id=1, name="doomed"))
    session.rollback()

    assert session.count(SnakeQuery(Widget)) == 0, (
        "the rollback did not reach the connection: the write survived"
    )


@pytest.mark.parametrize("stack", _STACKS)
def test_fetch_all_answers_a_LIST_on_every_engine(
    stack: str, request: pytest.FixtureRequest
) -> None:
    """The Protocol promises `list[tuple]`, and one driver of three used to answer a tuple.

    Bug #40, and the same family as #39: the declared type was not the one you got, on one engine.
    PyMySQL hands back a TUPLE of tuples and the driver returned it untouched — and everything
    downstream only ITERATES, so it went unnoticed until something compared the result to a list.

    Asserted as a type and not by contents: the rows were always right. What was wrong was the
    promise about their container.
    """
    session: SnakeSession = request.getfixturevalue(stack)
    driver = _driver_of(session)

    rows = driver.fetch_all(f"SELECT id FROM {_TABLE}", ())

    assert isinstance(rows, list), (
        f"{stack} answered a {type(rows).__name__} where the Protocol promises a list"
    )
